return {

    Elec = {
        "Base.AlarmClock",
        "Base.AlarmClock2",
        "Base.CDplayer",
        "Base.CordlessPhone",
        "Base.Earbuds",
        "Base.Headphones",
        "Base.NoiseTrap",
        "Base.NoiseTrapRemote",
        "Base.NoiseTrapSensorV1",
        "Base.NoiseTrapSensorV2",
        "Base.NoiseTrapSensorV3",
        "Base.NoiseTrapTriggered",
        "Base.Radio",
        "Base.Remote",
        "Base.RemoteCraftedV1",
        "Base.RemoteCraftedV2",
        "Base.RemoteCraftedV3",
        "Base.Speaker",
        "Base.TimerCrafted",
        "Base.VideoGame",
        "Radio.HamRadio1",
        "Radio.HamRadio2",
        "Radio.HamRadioMakeShift",
        "Radio.RadioBlack",
        "Radio.RadioMakeShift",
        "Radio.RadioRed",
        "Radio.TvAntique",
        "Radio.TvBlack",
        "Radio.TvWideScreen",
        "Radio.WalkieTalkie1",
        "Radio.WalkieTalkie2",
        "Radio.WalkieTalkie3",
        "Radio.WalkieTalkie4",
        "Radio.WalkieTalkie5",
        "Radio.WalkieTalkieMakeShift",
        "Base.Camera",
        "Base.CameraDisposable",
        "Base.CameraExpensive",
    },

    MediaA = {
        "Base.Disc_Retail",
        "Base.Disc",
    },

    MediaV = {
        "Base.VHS",
        "Base.VHS_Home",
        "Base.VHS_Retail",
    },

}