return {

    FoodA = {
        "CCS.MoonshineFull",
        "CCS.AbsintheFull",
        "CCS.Beer",
        "CCS.BeerCanSixPack",
        "CCS.SojuFull",
        "CCS.SakeFull",
        "CCS.GinFull",
        "CCS.VodkaFull",
        "CCS.BourbonFull",
        "CCS.BrandyFull",
        "CCS.ChampangneFull",
        "CCS.CognacFull",
        "CCS.RumFull",
        "CCS.TequilaFull",
        "CCS.WhiskeyBlackLabelFull",
        "CCS.WhiteWineFull",
        "CCS.DarkBeer",
        "CCS.DarkBeerCanSixPack",
        "CCS.TripleSecFull",
    },

    Cont = {
        "CCS.MoonshineEmpty",
        "CCS.AbsintheEmpty",
        "CCS.SojuEmpty",
        "CCS.SakeEmpty",
        "CCS.GinEmpty",
        "CCS.VodkaEmpty",
        "CCS.BourbonEmpty",
        "CCS.BrandyEmpty",
        "CCS.ChampangneEmpty",
        "CCS.CognacEmpty",
        "CCS.RumEmpty",
        "CCS.TequilaEmpty",
        "CCS.WhiskeyBlackLabelEmpty",
        "CCS.WhiteWineEmpty",
        "CCS.TripleSecEmpty",
    },

    FoodB = {
        "CCS.MoonshineBottleWater",
        "CCS.AbsintheWaterFull",
        "CCS.SojuWaterFull",
        "CCS.SakeWaterFull",
        "CCS.GinWaterFull",
        "CCS.VodkaVodka",
        "CCS.BourbonBottleWater",
        "CCS.BrandyBottleWater",
        "CCS.ChampangneBottleWater",
        "CCS.CognacBottleWater",
        "CCS.RumBottleWater",
        "CCS.TequilaBottleWater",
        "CCS.WhiskeyBlackLabelBottleWater",
        "CCS.WhiteWineBottleWater",
        "CCS.TripleSecBottleWater",
    },

    Junk = {
        "CCS.BeerCanEmpty",
        "CCS.DarkBeerCanEmpty",
    },

}