return {

    FoodN = {
        "Ramen.RamenChickenFlat",
        "Ramen.RamenChickenPack",
        "Ramen.RamenChickenFlav",
        "Ramen.RamenBeefFlat",
        "Ramen.RamenBeefPack",
        "Ramen.RamenBeefFlav",
        "Ramen.RamenShrimpFlat",
        "Ramen.RamenShrimpPack",
        "Ramen.RamenShrimpFlav",
        "Ramen.RamenCheeseFlat",
        "Ramen.RamenCheesePack",
        "Ramen.RamenCheeseFlav",
        "Ramen.RamenChiliFlat",
        "Ramen.RamenChiliPack",
        "Ramen.RamenChiliFlav",
        "Ramen.RamenOrientalFlat",
        "Ramen.RamenOrientalPack",
        "Ramen.RamenOrientalFlav",
        "Ramen.RamenPorkFlat",
        "Ramen.RamenPorkPack",
        "Ramen.RamenPorkFlav",
    },

    FoodP = {
        "Ramen.RamenChickenBowl",
        "Ramen.RamenBeefBowl",
        "Ramen.RamenShrimpBowl",
        "Ramen.RamenCheeseBowl",
        "Ramen.RamenChiliBowl",
        "Ramen.RamenOrientalBowl",
        "Ramen.RamenPorkBowl",
    },

    Junk = {
        "Ramen.RamenChickenFlatEmpty",
        "Ramen.RamenBeefFlatEmpty",
        "Ramen.RamenShrimpFlatEmpty",
        "Ramen.RamenCheeseFlatEmpty",
        "Ramen.RamenChiliFlatEmpty",
        "Ramen.RamenOrientalFlatEmpty",
        "Ramen.RamenPorkFlatEmpty",
        "Ramen.RamenChickenPackEmpty",
        "Ramen.RamenChickenFlavEmpty",
        "Ramen.RamenBeefPackEmpty",
        "Ramen.RamenBeefFlavEmpty",
        "Ramen.RamenShrimpPackEmpty",
        "Ramen.RamenShrimpFlavEmpty",
        "Ramen.RamenCheesePackEmpty",
        "Ramen.RamenCheeseFlavEmpty",
    },

}