return {

    Appear = {
        "filcher.HairDyeAuburn",
        "filcher.HairDyeAvocado",
        "filcher.HairDyeCherry",
        "filcher.HairDyeCyan",
        "filcher.HairDyeDarkBlue",
        "filcher.HairDyeDarkBrown",
        "filcher.HairDyeDarkTurquoise",
        "filcher.HairDyeDeepPurple",
        "filcher.HairDyeGrey",
        "filcher.HairDyeLightBlonde",
        "filcher.HairDyeLilac",
        "filcher.HairDyeLime",
        "filcher.HairDyeMagenta",
        "filcher.HairDyeOlive",
        "filcher.HairDyeOrange",
        "filcher.HairDyePurple",
        "filcher.HairDyeSnowWhite",
        "filcher.HairDyeTurquoise",
        "MoreSkillBooks.Other_Moustache",
    },

    Tool = {
        "filcher.SFChisel",
        "filcher.MasonsTrowel",
        "filcher.HandTruckBlue",
        "filcher.HandTruckRed",
        "filcher.BatteryLamp",
        "filcher.Flare",
        "filcher.GasLantern",
        "filcher.GasLanternEmpty",
        "filcher.GasLanternLit",
        "filcher.HeadTorch",
        "filcher.TorchBranch",
        "filcher.TorchBranchLit",
        "filcher.TorchChairLeg",
        "filcher.TorchChairLegLit",
        "filcher.TorchPlank",
        "filcher.TorchPlankLit",
        "filcher.TorchTableLeg",
        "filcher.TorchTableLegLit",
        "filcher.SFGrainGrinder",
    },

    LitS = {
        "filcher.BookMasonry1",
        "filcher.BookMasonry2",
        "filcher.BookMasonry3",
        "filcher.BookMasonry4",
        "filcher.BookMasonry5",
        "Base.BookPhotography1",
        "Base.BookPhotography2",
        "Base.BookPhotography3",
        "Base.BookPhotography4",
        "Base.BookPhotography5",
    },

    LitR = {
        "filcher.SFMasonMag",
        "filcher.SFMetalworkMag5",
        "filcher.SFCookingMag1",
        "filcher.SFCookingMag2",
        "filcher.SFCookingMag3",
        "filcher.SFCookingGuide",
        "filcher.SFBookFarm",
        "filcher.SFFarmMag2",
        "filcher.SFFarmMag3",
        "filcher.BookMaintenance1",
        "filcher.BookMaintenance2",
        "filcher.BookMaintenance3",
        "filcher.BookMaintenance4",
        "filcher.BookMaintenance5",
        "filcher.SFGuideCooking",
        "filcher.SFGuideEletronics",
        "filcher.SFGuideEngineering",
        "filcher.SFGuideFishing",
        "filcher.SFGuideMechanics",
        "filcher.SFGuideMetalworking",
        "filcher.SFGuideRadio",
        "filcher.SFGuideTrapping",
        "filcher.FarmingNotes1",
        "filcher.FarmingNotes2",
        "filcher.FarmingNotes3",
        "filcher.FishingNotes1",
        "filcher.FishingNotes2",
        "filcher.HuntingNotes1",
        "filcher.HuntingNotes2",
        "filcher.HuntingNotes3",
        "filcher.HerbalistNotes",
        "filcher.MetalworkNotes1",
        "filcher.MetalworkNotes2",
        "filcher.MetalworkNotes3",
        "filcher.MetalworkNotes4",
        "filcher.CookingNotes1",
        "filcher.CookingNotes2",
        "filcher.SFCookingNotes1",
        "filcher.ElectronicsNotes1",
        "filcher.ElectronicsNotes2",
        "filcher.ElectronicsNotes3",
        "filcher.ElectronicsNotes4",
        "filcher.ElectronicsNotes5",
        "filcher.EngineerNotes1",
        "filcher.EngineerNotes2",
        "filcher.EngineerNotes3",
        "filcher.EngineerNotes4",
        "filcher.EngineerNotes5",
        "filcher.MechanicNotes1",
        "filcher.MechanicNotes2",
        "filcher.MechanicNotes3",
        "filcher.RadioNotes1",
        "filcher.RadioNotes2",
        "filcher.RadioNotes3",
        "filcher.SmithingNotes1",
        "filcher.SmithingNotes2",
        "filcher.SmithingNotes3",
        "filcher.SmithingNotes4",
        "filcher.SmithingNotes5",
        "Base.SFPhotoMag",
    },

    CraftMas = {
        "filcher.Bricks",
        "filcher.SFBrickMold",
        "filcher.SFClay",
        "filcher.SFClayBag",
        "filcher.SFMoldedBricks",
        "filcher.SFSealant",
        "filcher.SFGlassPanel",
    },

    WepRange = {
        "filcher.NailGun",
    },

    WepMelee = {
        "filcher.PoolballInSock",
        "filcher.Recorder",
        "filcher.UmbrellaPink",
        "filcher.ClosedUmbrellaPink",
        "filcher.WalkingCane",
        "filcher.WoodenCross",
        "Base.Corkscrew",
    },

    Cook = {
        "filcher.SFBakingTrayCornbread",
        "filcher.SFBarbecue",
        "filcher.Cinnamon",
        "filcher.SFCornBatter",
        "filcher.SFCornbreadBatter",
        "filcher.SFCupcakeBatter",
        "filcher.SFCurry",
        "filcher.SFOregano",
        "filcher.SFPaprika",
        "filcher.SFPizzaDough",
        "filcher.SFPizzaPrep",
        "filcher.SFPlainBreadDough",
        "filcher.SFCupcakeTray",
        "filcher.EmptyGlass",
        "filcher.JarAndLid",
        "filcher.SFThinStick",
        "filcher.SFWheat",
        "filcher.TeaExtract",
    },

    FoodP = {
        "filcher.SFBasil",
        "filcher.Beercheese",
        "filcher.Beetroot",
        "filcher.BreadPieces",
        "filcher.SFCalabrese",
        "filcher.CannedHamOpen",
        "filcher.CannedSoupOpen",
        "filcher.OpenCannedSpagetti",
        "filcher.OpenCannedSpinach",
        "filcher.CannedBeetroot",
        "filcher.CannedPumpkin",
        "filcher.SFCatfoodOpen",
        "filcher.Cauliflower",
        "filcher.SFChocolateWaferStick",
        "filcher.SFChocolateWaferSticksJarOpen",
        "filcher.SFCornbread",
        "filcher.SFCorndogRaw",
        "filcher.SFCupcake",
        "filcher.SFCupcakes",
        "filcher.EggFried",
        "filcher.SFFig",
        "filcher.SFGuacamole",
        "filcher.SFHotdog",
        "filcher.IcecreamBowl",
        "filcher.SFKiwi",
        "filcher.SFPapaya",
        "filcher.SFPizzaRaw",
        "filcher.SFPizzaSlice",
        "filcher.SFPlainBreadCooked",
        "filcher.SFPopsicle",
        "filcher.SFPopsicle2",
        "filcher.SFPopsicle3",
        "filcher.SFPopsicle4",
        "filcher.SFPopsicle5",
        "filcher.SFPorkribs",
        "filcher.SFPotatoSliced",
        "filcher.PumpkinPieWholeRaw",
        "filcher.SFRosemary",
        "filcher.SFSausage",
        "filcher.Spoonbread",
        "filcher.Toasts",
        "filcher.SFTurnip",
        "filcher.SFRaspberry",
        "filcher.SFTruffles",
        "filcher.SFDeadCrow",
    },

    FoodN = {
        "filcher.SFBeans",
        "filcher.SFBeanBowl",
        "filcher.CannedHam",
        "filcher.CannedSoup",
        "filcher.CannedSpagetti",
        "filcher.CannedSpinach",
        "filcher.SFCatfood",
        "filcher.SFChili",
        "filcher.SFChocolateWaferSticksJar",
        "filcher.SFCupcakePrep",
        "filcher.DriedApricots",
        "filcher.SFHazelnutCream",
        "filcher.SFIcecreamEvolved",
        "filcher.SFJelly",
        "filcher.Macaroni",
        "filcher.Olives",
        "filcher.SFPickles",
        "filcher.SFPicklingJar",
        "filcher.SFPlainBreadRotten",
        "filcher.SFPopsicleMelted",
        "filcher.SFPopsicle2Melted",
        "filcher.SFPopsicle3Melted",
        "filcher.SFPopsicle4Melted",
        "filcher.SFPopsicle5Melted",
        "filcher.SaucepanFries",
        "filcher.SFTomatoSauce",
        "filcher.SFWaterPotBeans",
        "filcher.SFWhippedCream",
        "filcher.SFBeetSyrupPot",
        "filcher.SFBeetPot",
        "filcher.TeaLeaves",
        "filcher.SFAcorns",
        "filcher.SFHickoryNut",
        "filcher.SFHoney",
        "filcher.SFPawpaw",
        "filcher.SFPersimmon",
        "filcher.SFPineNuts",
        "filcher.SFPlum",
    },

    FoodB = {
        "filcher.SFBoxOfTea",
        "filcher.SFDrink",
        "filcher.SFDrinkBase",
        "filcher.SFJuice",
        "filcher.Lemonade",
        "filcher.WaterGlass",
        "Base.BeerCanWater",
        "Base.FountainCupWater",
        "Base.JarWater",
        "Base.PetrolCanWater",
        "Base.PlasticCupWater",
        "Base.PopCanWater",
        "Base.Pop2CanWater",
        "Base.Pop3CanWater",
        "Base.RoastingPanWater",
        "Base.TinCanWater",
        "Base.WaterDishFull",
        "Base.WaterGallon",
        "filcher.SFIceTray",
        "filcher.TinCanWater",
        "filcher.SFWaterTray",
    },

    ClothBag = {
        "MoreSkillBooks.Bag_FannyPackTINTFront",
        "MoreSkillBooks.Bag_FannyPackTINTBack",
    },

    ClothBack = {
        "MoreSkillBooks.Bag_NormalHikingBagTINT",
        "MoreSkillBooks.Bag_BigHikingBagTINT",
        "MoreSkillBooks.Bag_SchoolbagTINT",
    },

    Cont = {
        "MoreSkillBooks.Bag_ToteSF",
        "MoreSkillBooks.Bag_ToteSFXmas",
        "MoreSkillBooks.Bag_ToteSFWeen",
        "Base.WaterGallonEmpty",
        "filcher.SFEmptyTray",
        "filcher.Briefcase",
    },

    ClothAcc = {
        "MoreSkillBooks.Belt_Black",
        "MoreSkillBooks.Belt_TINT",
        "MoreSkillBooks.Belt_Tools",
        "MoreSkillBooks.Other_BunnyTail",
        "MoreSkillBooks.Other_RaccoonTail",
        "MoreSkillBooks.Scarf_PureWhite",
        "MoreSkillBooks.Scarf_StripedGreenWhite",
        "MoreSkillBooks.Scarf_StripedRedGreen",
        "MoreSkillBooks.Scarf_StripedRedYellow",
        "MoreSkillBooks.Tie_Full_Black",
        "MoreSkillBooks.Tie_FullTINT",
    },

    ClothBody = {
        "MoreSkillBooks.SkeletonSuit",
        "MoreSkillBooks.SlendermanSuit",
        "MoreSkillBooks.Dress_Cardinals",
        "MoreSkillBooks.Dress_Fancy",
        "MoreSkillBooks.Dress_Mini",
        "MoreSkillBooks.FancyJacket",
        "MoreSkillBooks.Jacket_Brown",
        "MoreSkillBooks.Jacket_Red",
        "MoreSkillBooks.Apron_TINT",
        "MoreSkillBooks.Swimsuit_SexyBunny",
        "MoreSkillBooks.Swimsuit_SexyTINT",
        "MoreSkillBooks.Tshirt_CutBellyWHITE",
        "MoreSkillBooks.Tshirt_CutBellyTINT",
        "MoreSkillBooks.Tshirt_MiscDECALTINT",
        "MoreSkillBooks.Tshirt_MiscDECALWHITE",
        "MoreSkillBooks.Tshirt_SleevelessWHITE",
        "MoreSkillBooks.Tshirt_SleevelessTINT",
        "MoreSkillBooks.Tshirt_LongTranspBlack",
        "MoreSkillBooks.Tshirt_WhiteTINT_OUT",
        "MoreSkillBooks.Vest_WaistcoatWHITE",
        "MoreSkillBooks.Vest_WaistcoatDarkGreen",
        "MoreSkillBooks.Vest_WaistcoatDarkRed",
        "MoreSkillBooks.Vest_WaistcoatGreen",
        "MoreSkillBooks.Vest_WaistcoatRed",
        "MoreSkillBooks.Vest_WaistcoatTartan",
    },

    ClothLeg = {
        "MoreSkillBooks.Skirt_Ballet",
        "MoreSkillBooks.Skirt_KneesTartan",
        "MoreSkillBooks.Skirt_Santa",
        "MoreSkillBooks.Skirt_SantaGreen",
        "MoreSkillBooks.DungareesShort",
        "MoreSkillBooks.DungareesShortTINT",
        "MoreSkillBooks.DungareesWhite",
        "MoreSkillBooks.DungareesTINT",
        "MoreSkillBooks.Shorts_MiniDenim",
        "MoreSkillBooks.Shorts_MiniDenimBlack",
        "MoreSkillBooks.Shorts_MiniDenimLight",
        "MoreSkillBooks.Trousers_TightDenim",
        "MoreSkillBooks.Trousers_TightDenimBlack",
        "MoreSkillBooks.Trousers_TightDenimLight",
    },

    ClothHead = {
        "MoreSkillBooks.Glasses_3D",
        "MoreSkillBooks.Glasses_TINT",
        "MoreSkillBooks.Glasses_White",
        "MoreSkillBooks.Hat_BaseballCapSpiffo",
        "MoreSkillBooks.Hat_BaseballCapSpiffo_Reverse",
        "MoreSkillBooks.Hat_BaseballCapTINT",
        "MoreSkillBooks.Hat_BaseballCapTINT_Reverse",
        "MoreSkillBooks.Hat_BaseballCapVote",
        "MoreSkillBooks.Hat_BaseballCapVote_Reverse",
        "MoreSkillBooks.Hat_BaseballCapWhite",
        "MoreSkillBooks.Hat_BaseballCapWhite_Reverse",
        "MoreSkillBooks.Hat_BunnyEars",
        "MoreSkillBooks.Hat_Bucket",
        "MoreSkillBooks.Hat_CookingPot",
        "MoreSkillBooks.Hat_DinoHat",
        "MoreSkillBooks.Hat_Fox",
        "MoreSkillBooks.Hat_HeadbandSimpleTINT",
        "MoreSkillBooks.Hat_MickeyEars",
        "MoreSkillBooks.Hat_TopHat",
        "MoreSkillBooks.Hat_Wig",
        "MoreSkillBooks.Hat_WoolyHatCartman",
        "MoreSkillBooks.Hat_WoolyHatDouble",
        "MoreSkillBooks.Hat_WoolyHatXmas",
        "MoreSkillBooks.Other_ClownNose",
    },

    Elec = {
        "MoreSkillBooks.WristWatch_Right_DigitalBlue",
        "MoreSkillBooks.WristWatch_Left_DigitalBlue",
        "Base.CameraReady",
        "Base.CameraDisposable",
        "Base.CameraExpensiveReady",
    },

    ClothArm = {
        "MoreSkillBooks.Gloves_White",
        "MoreSkillBooks.Gloves_Yellow",
    },

    ClothMisc = {
        "MoreSkillBooks.Other_Billboard",
        "MoreSkillBooks.Other_BillboardGod",
        "MoreSkillBooks.Other_BillboardVote",
        "MoreSkillBooks.Other_Floatsie",
        "MoreSkillBooks.Other_FloatsieFlamingo",
    },

    ClothFeet = {
        "MoreSkillBooks.Sock_Ankle_Left",
        "MoreSkillBooks.Sock_Ankle_Right",
        "MoreSkillBooks.Sock_Long_Left",
        "MoreSkillBooks.Sock_Long_Right",
        "MoreSkillBooks.Socks_LegWarmers",
        "MoreSkillBooks.Shoes_BootsTINT",
        "MoreSkillBooks.Shoes_Clown",
        "MoreSkillBooks.Shoes_SantaBoots",
        "MoreSkillBooks.Socks_Ballet",
        "MoreSkillBooks.Socks_StockingsBlack",
    },

    Fuel = {
        "filcher.BottleWithGasPop",
        "filcher.BottleWithGasWater",
    },

    SurFarm = {
        "filcher.BeetSeed",
        "filcher.BeetBagSeed",
        "filcher.CornSeed",
        "filcher.CornBagSeed",
        "filcher.CauliflowerSeed",
        "filcher.CauliflowerBagSeed",
        "filcher.SFLemonGrassSeed",
        "filcher.SFLemonGrassBagSeed",
        "filcher.LettuceSeed",
        "filcher.LettuceBagSeed",
        "filcher.TeaSeed",
        "filcher.TeaBagSeed",
        "filcher.SFWheatSeed",
        "filcher.SFWheatBagSeed",
        "filcher.GardeningSprayCigarettes",
        "filcher.GardeningSprayMilk",
    },

    Junk = {
        "filcher.SFCloth",
        "filcher.SFClothDirty",
        "filcher.SFThermometer",
        "filcher.GiftCard",
        "filcher.PostcardLocal",
        "filcher.PostcardOthers",
        "filcher.RippedPages",
        "filcher.SFChessboard",
        "filcher.SFLetter",
        "filcher.Magic8Ball",
        "Base.CameraFilm",
        "Base.CameraFilmRevealed",
        "Base.Picture",
    },

    Drugs = {
        "filcher.Cigarette",
    },

    Craft = {
        "filcher.SFBucketSnow",
        "filcher.SnowPaintbucket",
        "filcher.SnowPot",
        "filcher.TinCanSnow",
    },

    Misc = {
        "filcher.SFSnowball",
    },

    LitE = {
        "filcher.ColoringBook",
        "filcher.Crosswords",
        "filcher.SFLetterToYou",
        "filcher.NotesJokes",
        "filcher.Novel",
    },

    LitW = {
        "filcher.GreenPen",
        "filcher.MulticolorPen",
        "Base.PhotographicPaper",
    },

}