return {

    Med = {
        "GidOrganized.OS12pkAdhesiveBandages",
        "GidOrganized.OS30pkAlcoholWipes",
        "GidOrganized.OS30pkAntibiotics",
        "GidOrganized.OS50pkAntidepressants",
        "GidOrganized.OS9pkBandages",
        "GidOrganized.OS9pkBandagesDirty",
        "GidOrganized.OS50pkBetaBlockers",
        "GidOrganized.OS12pkCottonBalls",
        "GidOrganized.OS4pkDisinfectant",
        "GidOrganized.OS50pkPainkillers",
        "GidOrganized.OS50pkSleepingPills",
        "GidOrganized.OS9pkSterileBandages",
        "Packing.10pkTissue",
        "Packing.5pkTissue",
        "Packing.4pkToiletPaper",
        "GidOrganized.OS50pkVitamins",
    },

    Craft = {
        "Packing.10pkBarbedWire",
        "Packing.5pkBarbedWire",
        "Packing.10pkBattery",
        "Packing.5pkBattery",
        "Packing.10pkRopeBranch",
        "Packing.5pkRopeBranch",
        "Packing.10pkSheetRopeBranch",
        "Packing.5pkSheetRopeBranch",
        "GidOrganizedFood.OS4pkDuctTape",
        "Packing.10pkGarbage",
        "Packing.5pkGarbage",
        "Packing.10pkGlue",
        "Packing.5pkGlue",
        "Packing.10pkNailsBox",
        "Packing.5pkNailsBox",
        "Packing.10pkRopePropaneTank",
        "Packing.5pkRopePropaneTank",
        "Packing.10pkSheetRopePropaneTank",
        "Packing.5pkSheetRopePropaneTank",
        "Packing.10pkRope",
        "Packing.5pkRope",
        "Packing.10pkScrewsBox",
        "Packing.5pkScrewsBox",
        "Packing.10pkSheetRope",
        "Packing.5pkSheetRope",
        "Packing.10pkTwine",
        "Packing.5pkTwine",
        "Packing.10pkWire",
        "Packing.5pkWire",
        "Packing.10pkWoodGlue",
        "Packing.5pkWoodGlue",
    },

    FoodA = {
        "Packing.6pkBeer",
        "Packing.6pkBeerCan",
        "Packing.10pkRedWine",
        "Packing.5pkRedWine",
        "Packing.10pkWhiskey",
        "Packing.5pkWhiskey",
        "Packing.10pkWhiteWine",
        "Packing.5pkWhiteWine",
    },

    LitW = {
        "Packing.10pkBluePen",
        "Packing.5pkBluePen",
        "Packing.10pkNotebook",
        "Packing.5pkNotebook",
        "Packing.10pkPen",
        "Packing.5pkPen",
        "Packing.10pkPencil",
        "Packing.5pkPencil",
        "Packing.10pkRedPen",
        "Packing.5pkRedPen",
        "Packing.10pkSheetPaper",
        "Packing.5pkSheetPaper",
    },

    LitE = {
        "Packing.10pkBook",
        "Packing.5pkBook",
        "Packing.10pkMagazine",
        "Packing.5pkMagazine",
        "Packing.10pkNewspaper",
        "Packing.5pkNewspaper",
    },

    FoodN = {
        "GidOrganizedFood.OS6pkCannedBeans",
        "GidOrganizedFood.OS6pkCannedBolognese",
        "GidOrganizedFood.OS6pkCannedCarrots",
        "GidOrganizedFood.OS6pkCannedChili",
        "GidOrganizedFood.OS6pkCannedCorn",
        "GidOrganizedFood.OS6pkCannedCornedBeef",
        "Packing.6pkCannedFruitBeverage",
        "Packing.6pkCannedFruitCocktail",
        "Packing.6pkCannedMilk",
        "GidOrganizedFood.OS6pkCannedMushSoup",
        "Packing.6pkCannedPeaches",
        "GidOrganizedFood.OS6pkCannedPeas",
        "Packing.6pkCannedPineapple",
        "GidOrganizedFood.OS6pkCannedPotato",
        "GidOrganizedFood.OS4pkSardines",
        "GidOrganizedFood.OS6pkCannedSoup",
        "GidOrganizedFood.OS6pkCannedTomato",
        "GidOrganizedFood.OS8pkCannedTuna",
        "Packing.6pkDogFood",
    },

    Drugs = {
        "Packing.20pkCigarettes",
    },

    Cook = {
        "GidOrganizedFood.OS4pkCoffee",
    },

    CraftTailor = {
        "Packing.10pkDenim",
        "Packing.50pkDenim",
        "Packing.100pkDenim",
        "Packing.10pkLeather",
        "Packing.50pkLeather",
        "Packing.100pkLeather",
        "Packing.10pkRag",
        "Packing.50pkRag",
        "Packing.100pkRag",
        "Packing.10pkThread",
        "Packing.5pkThread",
    },

    CraftElec = {
        "Packing.10pkElectricWire",
        "Packing.5pkElectricWire",
        "Packing.10pkElectronicsScrap",
        "Packing.50pkElectronicsScrap",
        "Packing.100pkElectronicsScrap",
    },

    SurFish = {
        "Packing.10pkFishingLine",
        "Packing.5pkFishingLine",
        "Packing.10pkFishingNet",
        "Packing.5pkFishingNet",
    },

    Tool = {
        "Packing.10pkLighter",
        "Packing.5pkLighter",
        "Packing.10pkMatches",
        "Packing.5pkMatches",
    },

    CraftMetal = {
        "Packing.10pkMetalBar",
        "Packing.5pkMetalBar",
        "Packing.10pkRopeMetalBar",
        "Packing.5pkRopeMetalBar",
        "Packing.10pkSheetRopeMetalBar",
        "Packing.5pkSheetRopeMetalBar",
        "Packing.10pkMetalPipe",
        "Packing.5pkMetalPipe",
        "Packing.10pkRopeMetalPipe",
        "Packing.5pkRopeMetalPipe",
        "Packing.10pkSheetRopeMetalPipe",
        "Packing.5pkSheetRopeMetalPipe",
        "Packing.10pkScrapMetal",
        "Packing.5pkScrapMetal",
        "Packing.10pkSheetMetal",
        "Packing.5pkSheetMetal",
        "Packing.10pkRopeSheetMetal",
        "Packing.5pkRopeSheetMetal",
        "Packing.10pkSheetRopeSheetMetal",
        "Packing.5pkSheetRopeSheetMetal",
        "Packing.10pkSheetMetalSmall",
        "Packing.5pkSheetMetalSmall",
        "Packing.10pkWeldingRods",
        "Packing.5pkWeldingRods",
    },

    FoodB = {
        "Packing.10pkOrangeSoda",
        "Packing.5pkOrangeSoda",
        "GidOrganizedFood.OS6pkPop",
        "GidOrganizedFood.OS6pkPopDiet",
        "GidOrganizedFood.OS6pkFizz",
        "GidOrganizedFood.OS24pkWaterBottleFull",
    },

    Mech = {
        "Packing.10pkRopePetrolCan",
        "Packing.5pkRopePetrolCan",
        "Packing.10pkSheetRopePetrolCan",
        "Packing.5pkSheetRopePetrolCan",
        "Packing.10pkRopeEmptyPetrolCan",
        "Packing.5pkRopeEmptyPetrolCan",
    },

    Cont = {
        "Packing.10pkSheetRopeEmptyPetrolCan",
        "Packing.5pkSheetRopeEmptyPetrolCan",
        "GidOrganizedFood.OS24pkWaterBottleEmpty",
        "GidOrganizedFood.OS8pkWhiskeyEmpty",
        "GidOrganizedFood.OS12pkWineEmpty",
        "GidOrganizedFood.OS12pkWineEmpty2",
    },

    CraftCarp = {
        "Packing.10pkSheetRopePlank",
        "Packing.5pkSheetRopePlank",
        "Packing.10pkRopePlank",
        "Packing.5pkRopePlank",
    },

    LitS = {
        "Packing.pkCarpentry",
        "Packing.pkCooking",
        "Packing.pkElectricity",
        "Packing.pkFarming",
        "Packing.pkFirstaid",
        "Packing.pkFishing",
        "Packing.pkForaging",
        "Packing.pkMechanics",
        "Packing.pkTailoring",
        "Packing.pkMetalwork",
        "Packing.pkTrapping",
    },

    Clean = {
        "Packing.10pkSoap",
        "Packing.5pkSoap",
    },

    Ammo = {
        "Packing.10pk223",
        "Packing.5pk223",
        "Packing.10pk308",
        "Packing.5pk308",
        "Packing.10pk38",
        "Packing.5pk38",
        "Packing.10pk44",
        "Packing.5pk44",
        "Packing.10pk45",
        "Packing.5pk45",
        "Packing.10pk556",
        "Packing.5pk556",
        "Packing.10pk9",
        "Packing.5pk9",
        "Packing.10pkShotgun",
        "Packing.5pkShotgun",
    },

}