return {

    LitR = {
        "PaintYourRide.VehiclePaintingMag1",
        "PaintYourRide.VehiclePaintingMag2",
    },

    Paint = {
        "PaintYourRide.SprayGun",
        "PaintYourRide.WireBrush",
        "PaintYourRide.CataloguePaintSpray",
        "PaintYourRide.CataloguePaintTints",
        "PaintYourRide.BoxAutomotivePaintTints",
        "PaintYourRide.BoxAutomotivePaintSprays1",
        "PaintYourRide.BoxAutomotivePaintSprays2",
        "PaintYourRide.BoxAutomotivePaintSprays3",
        "PaintYourRide.BoxAutomotivePaintSprays4",
        "PaintYourRide.AutomotivePaintBucketEmpty",
        "PaintYourRide.AutomotivePaintWhite",
        "PaintYourRide.AutomotivePaintBottleEmpty",
        "PaintYourRide.AutomotiveTintPaintBlack",
        "PaintYourRide.AutomotiveTintPaintBlue",
        "PaintYourRide.AutomotiveTintPaintCyan",
        "PaintYourRide.AutomotiveTintPaintGreen",
        "PaintYourRide.AutomotiveTintPaintMagenta",
        "PaintYourRide.AutomotiveTintPaintRed",
        "PaintYourRide.AutomotiveTintPaintYellow",
        "PaintYourRide.AutomotiveSprayCanEmpty",
        "PaintYourRide.AutomotiveSprayPrimer",
        "PaintYourRide.AutomotiveSprayPaintBlack",
        "PaintYourRide.AutomotiveSprayPaintBlue",
        "PaintYourRide.AutomotiveSprayPaintBlueNavy",
        "PaintYourRide.AutomotiveSprayPaintBlueNeon",
        "PaintYourRide.AutomotiveSprayPaintBlueOlympic",
        "PaintYourRide.AutomotiveSprayPaintBrownDarkChocolate",
        "PaintYourRide.AutomotiveSprayPaintBrownRusty",
        "PaintYourRide.AutomotiveSprayPaintGreen",
        "PaintYourRide.AutomotiveSprayPaintGreenArmy",
        "PaintYourRide.AutomotiveSprayPaintGreenForest",
        "PaintYourRide.AutomotiveSprayPaintGreenNeon",
        "PaintYourRide.AutomotiveSprayPaintGrey",
        "PaintYourRide.AutomotiveSprayPaintGreySteel",
        "PaintYourRide.AutomotiveSprayPaintOrangeTangerine",
        "PaintYourRide.AutomotiveSprayPaintPinkBubbleGum",
        "PaintYourRide.AutomotiveSprayPaintPinkGlamorous",
        "PaintYourRide.AutomotiveSprayPaintRed",
        "PaintYourRide.AutomotiveSprayPaintRedBurgundy",
        "PaintYourRide.AutomotiveSprayPaintRedCandyApple",
        "PaintYourRide.AutomotiveSprayPaintVioletGrape",
        "PaintYourRide.AutomotiveSprayPaintVioletIndigo",
        "PaintYourRide.AutomotiveSprayPaintWhite",
        "PaintYourRide.AutomotiveSprayPaintYellow",
        "PaintYourRide.AutomotiveSprayPaintYellowNeon",
        "PaintYourRide.AutomotiveSprayPaintYellowTuscany",
    },

}