return {

    ClothFeet = {
        "Base.AssaultBoots",
        "Base.AssaultBootsDesert",
    },

    ClothAcc = {
        "Base.CalfSheath",
        "Base.AmmoStrap_Bullets",
        "Base.AmmoStrap_Shells",
        "Base.ShotgunShellBandolier",
        "Base.BulletBandolier",
        "Base.ThighHolsterSimple",
        "Base.ThighHolsterDouble",
        "Keytool.KeyRing",
    },

    ClothBody = {
        "Base.BackRig",
        "Base.Jacket_Black",
        "Base.CCVest",
        "Base.ChestRig",
        "Base.Webbing",
        "Base.WebbingLoose",
        "Base.Webbing_Military",
        "Base.Webbing_MilitaryLoose",
        "Base.Webbing_Black",
        "Base.Webbing_BlackLoose",
        "Base.Vest_BulletEMS",
        "Base.Vest_BulletFire",
        "Base.Vest_BulletPress",
        "Base.Vest_Waistcoat",
        "Base.Vest_Waistcoat_GigaMart",
        "Base.Vest_Hunting_Grey",
        "Base.Vest_Hunting_Orange",
        "Base.Vest_Hunting_Camo",
        "Base.Vest_Hunting_CamoGreen",
        "Base.Vest_Foreman",
    },

    Junk = {
        "Base.FactionBanner",
        "Base.WD40Empty",
        "Base.BrushkitEmpty",
        "Base.MaintkitEmpty",
        "Base.MRE_PorkwithRiceinBBQSauce_Finished",
        "Base.MRE_CornedBeefHash_Finished",
        "Base.MRE_ChickenStew_Finished",
        "Base.MRE_OmeletwithHam_Finished",
        "Base.MRE_SpaghettiwithMeatSauce_Finished",
        "Base.MRE_ChickenalaKing_Finished",
        "Base.MRE_BeefStew_Finished",
        "Base.MRE_HamSlice_Finished",
        "Base.MRE_MeatballswithTomatoSauce_Finished",
        "Base.MRE_TunawithNoodles_Finished",
        "Base.MRE_ChickenwithRice_Finished",
        "Base.MRE_EscallopedPotatoeswithHam_Finished",
        "Base.Small_Cardboard_Box",
        "Base.MRE_Box",
        "Base.MRE_Pouch_Trash",
        "Base.MRE_Drink_Trash",
        "Base.MRE_Cocoa_Trash",
        "Base.MRE_Coffee_Trash",
        "Base.MRE_Crackers_Trash",
        "Base.MRE_Spread_Trash",
        "Base.MRE_Meal_Pouch_Trash",
        "Base.MRE_Meal_Carton_Trash",
        "Base.MRE_Side_Pouch_Trash",
        "Base.MRE_Side_Carton_Trash",
        "Base.MRE_FlamelessRationHeater_Trash",
        "Trap.Nothing",
    },

    CraftTailor = {
        "Base.CeramicPlate",
        "Base.KevlarPlate",
        "Base.TitaniumPlate",
        "Movables.camo_netting_0",
    },

    Tool = {
        "Base.Compass",
        "Base.Compass2",
        "Base.CliponCompass",
        "Base.WristCompass_Right",
        "Base.WristCompass_Left",
        "Base.WD40",
        "Base.Brushkit",
        "Base.Maintkit",
        "Base.SAK",
        "Base.Multitool",
        "Base.P38",
        "Base.Leatherdad",
        "Base.P38DT",
        "Base.Flashlight_Military",
        "Base.MRE_FlamelessRationHeater",
        "Trap.PropaneTrap",
        "Trap.BearTrap",
        "Trap.BearTrapClosed",
        "Trap.SpikeTrap",
        "Trap.SpikeTrapClosed",
        "Base.PA_SlimJim",
    },

    WepBomb = {
        "Base.ConcussionGrenade",
        "Base.StunGrenade",
        "Base.IncendiaryGrenade",
        "Explosives.LandMine",
        "Explosives.LandMineSet",
        "Explosives.LandMineBig",
        "Explosives.LandMineBigSet",
        "Explosives.LandMineBigBox",
        "Explosives.LandMineBox",
        "Base.SmokeGrenade",
    },

    WepFire = {
        "Base.FlareGun",
        "Base.DoubleBarrelShotgunSawnOff2",
        "Base.VarmintRifleSawnOff",
        "Base.HuntingRifleSawnOff",
    },

    Ammo = {
        "Base.FlareCartridge",
        "Base.FlareCartridgeBox",
    },

    ClothHead = {
        "Base.SniperVeil",
        "Base.BallisticMask",
        "Base.SkullHalfMask",
    },

    Collect = {
        "Base.IntelFolder",
        "Base.BlackwebDiskette",
        "Base.LabKeycard",
    },

    WepMelee = {
        "Base.Knuckleduster",
        "Base.Kukri",
        "Base.PA_TacticalKukri",
        "Base.PA_TrenchKnife",
        "Base.PA_TrenchKnifeB",
        "Base.PA_TrenchKnifeC",
        "Base.PA_TrenchKnife2",
        "Base.PA_TrenchKnifeB2",
        "Base.PA_TrenchKnifeC2",
        "Base.PLGR",
    },

    Cont = {
        "Base.Canteen",
        "Base.MRE_Coffee_Mug",
        "Base.MRE_Coffee_Mug_Red",
        "Base.MRE_Coffee_Mug_White",
        "Base.MRE_Coffee_Mug_Spiffo",
    },

    FoodB = {
        "Base.Canteenfull",
        "Base.MRE_Coffee",
        "Base.Mugfull",
        "Base.MRE_SugarFreeBev_WaterBottle",
        "Base.MRE_BevwithSugar_WaterBottle",
        "Base.MRE_Cocoa_Mug",
        "Base.MRE_Cocoa_Mug_Red",
        "Base.MRE_Cocoa_Mug_White",
        "Base.MRE_Cocoa_Mug_Spiffo",
        "Base.MRE_BevwithSugar_Mug",
        "Base.MRE_BevwithSugar_Mug_Red",
        "Base.MRE_BevwithSugar_Mug_White",
        "Base.MRE_BevwithSugar_Mug_Spiffo",
        "Base.MRE_SugarFreeBev_Mug",
        "Base.MRE_SugarFreeBev_Mug_Red",
        "Base.MRE_SugarFreeBev_Mug_White",
        "Base.MRE_SugarFreeBev_Mug_Spiffo",
    },

    Cook = {
        "Base.WaterPurificationTablets",
        "Base.WaterPurificationTablets_Empty",
        "Base.MRE_Cocoa",
        "Base.MRE_BevBasewithSugar",
        "Base.MRE_SugarFreeBevBase",
    },

    FoodN = {
        "Base.MRE_Crackers",
        "Base.MRE_Jelly",
        "Base.MRE_PeanutButter",
        "Base.MRE_Cheesespread",
        "Base.MRE_PorkwithRiceinBBQSauce",
        "Base.MRE_CornedBeefHash",
        "Base.MRE_ChickenStew",
        "Base.MRE_OmeletwithHam",
        "Base.MRE_SpaghettiwithMeatSauce",
        "Base.MRE_ChickenalaKing",
        "Base.MRE_BeefStew",
        "Base.MRE_HamSlice",
        "Base.MRE_MeatballswithTomatoSauce",
        "Base.MRE_TunawithNoodles",
        "Base.MRE_ChickenwithRice",
        "Base.MRE_EscallopedPotatoeswithHam",
        "Base.MRE_PorkwithRiceinBBQSauce_Open",
        "Base.MRE_CornedBeefHash_Open",
        "Base.MRE_ChickenStew_Open",
        "Base.MRE_OmeletwithHam_Open",
        "Base.MRE_SpaghettiwithMeatSauce_Open",
        "Base.MRE_ChickenalaKing_Open",
        "Base.MRE_BeefStew_Open",
        "Base.MRE_HamSlice_Open",
        "Base.MRE_MeatballswithTomatoSauce_Open",
        "Base.MRE_TunawithNoodles_Open",
        "Base.MRE_ChickenwithRice_Open",
        "Base.MRE_EscallopedPotatoeswithHam_Open",
        "Base.MRE_PorkwithRiceinBBQSauce_Heating",
        "Base.MRE_CornedBeefHash_Heating",
        "Base.MRE_ChickenStew_Heating",
        "Base.MRE_OmeletwithHam_Heating",
        "Base.MRE_SpaghettiwithMeatSauce_Heating",
        "Base.MRE_ChickenalaKing_Heating",
        "Base.MRE_BeefStew_Heating",
        "Base.MRE_HamSlice_Heating",
        "Base.MRE_MeatballswithTomatoSauce_Heating",
        "Base.MRE_TunawithNoodles_Heating",
        "Base.MRE_ChickenwithRice_Heating",
        "Base.MRE_EscallopedPotatoeswithHam_Heating",
        "Base.Peanut_Butter_Patrol_Cookie",
        "Base.MRE_Stack",
        "Base.MRE",
        "Base.MRE_Side",
        "Base.MRE_Applesauce",
        "Base.MRE_Freezedriedfruit",
        "Base.MRE_PotatoesAuGrautin",
        "Base.MRE_OatmealCookieBar",
        "Base.MRE_PoundCake",
        "Base.MRE_BrownieChocCovered",
        "Base.MRE_CookieChocCovered",
        "Base.MRE_ChowMeinNoodles",
        "Base.MRE_PotatoSticks",
    },

    FoodP = {
        "Base.MRE_Crackers_Jelly",
        "Base.MRE_Crackers_PeanutButter",
        "Base.MRE_Crackers_Cheesespread",
        "Base.MRE_PorkwithRiceinBBQSauce_Hot",
        "Base.MRE_CornedBeefHash_Hot",
        "Base.MRE_ChickenStew_Hot",
        "Base.MRE_OmeletwithHam_Hot",
        "Base.MRE_SpaghettiwithMeatSauce_Hot",
        "Base.MRE_ChickenalaKing_Hot",
        "Base.MRE_BeefStew_Hot",
        "Base.MRE_HamSlice_Hot",
        "Base.MRE_MeatballswithTomatoSauce_Hot",
        "Base.MRE_TunawithNoodles_Hot",
        "Base.MRE_ChickenwithRice_Hot",
        "Base.MRE_EscallopedPotatoeswithHam_Hot",
        "Base.MRE_PorkwithRiceinBBQSauce_Hot_HotSauce",
        "Base.MRE_CornedBeefHash_Hot_HotSauce",
        "Base.MRE_ChickenStew_Hot_HotSauce",
        "Base.MRE_OmeletwithHam_Hot_HotSauce",
        "Base.MRE_SpaghettiwithMeatSauce_Hot_HotSauce",
        "Base.MRE_ChickenalaKing_Hot_HotSauce",
        "Base.MRE_BeefStew_Hot_HotSauce",
        "Base.MRE_HamSlice_Hot_HotSauce",
        "Base.MRE_MeatballswithTomatoSauce_Hot_HotSauce",
        "Base.MRE_TunawithNoodles_Hot_HotSauce",
        "Base.MRE_ChickenwithRice_Hot_HotSauce",
        "Base.MRE_EscallopedPotatoeswithHam_Hot_HotSauce",
        "Base.Paratrooper_Potluck_Pie",
        "Base.MRE_Fruit",
    },

    ClothBack = {
        "Base.Bag_Schoolbag_WithAttachment",
        "Base.Bag_NormalHikingBag_WithAttachment",
        "Base.Bag_NormalHikingBag_With2Attachments",
        "Base.Bag_BigHikingBag_WithAttachment",
        "Base.Bag_BigHikingBag_With2Attachments",
        "Base.Bag_SurvivorBag_WithAttachment",
        "Base.Bag_SurvivorBag_With2Attachments",
        "Base.Bag_SurvivorBag_With3Attachments",
        "Base.Bag_ALICEpack_WithAttachment",
        "Base.Bag_ALICEpack_With2Attachments",
        "Base.Bag_ALICEpack_With3Attachments",
        "Base.Bag_ALICEpack_Army_WithAttachment",
        "Base.Bag_ALICEpack_Army_With2Attachments",
        "Base.Bag_ALICEpack_Army_With3Attachments",
    },

    ClothBag = {
        "Base.Fanny_Pack_Blue",
        "Base.Fanny_Pack_Green",
        "Base.Fanny_Pack_Pink",
        "Base.Fanny_Pack_Red",
        "Base.Fanny_Pack_Teal",
        "Base.MVest_Red",
        "Base.MVest2_Red",
        "Base.SWATPouch_Paramedic",
    },

    Appear = {
        "Base.MakeUp_GreenCamo",
        "Base.MakeUp_GreenCamo2",
    },

    LitR = {
        "Base.PA_TrueCrimeMag2",
        "Base.PA_TrueCrimeMag2_b",
    },

}