return {

    WepPart = {
        "Base.x2Scope",
        "Base.x4Scope",
        "Base.x8Scope",
        "Base.Sling",
        "Base.RecoilPad",
        "Base.Bipod",
        "Base.RedDot",
        "Base.ShellHolder",
        "Base.Laser",
        "Base.ChokeTubeFull",
        "Base.ChokeTubeImproved",
        "Base.IronSight",
        "Base.FiberglassStock",
        "Base.OilFilterSuppressor",
        "Base.OilFilterSuppressor2",
        "Base.AmmoStraps",
        "Base.Coupled556",
        "Base.Coupled762",
    },

    WepFire = {
        "Base.Shotgun",
        "Base.ShotgunSawnoff",
        "Base.ShotgunSawnoffNoStock",
        "Base.DoubleBarrelShotgun",
        "Base.DoubleBarrelShotgunSawnoff",
        "Base.Spas12",
        "Base.Spas12Folded",
        "Base.AK47",
        "Base.AK47Folded",
        "Base.SKS",
        "Base.1022",
        "Base.Mini14",
        "Base.Mini14Folded",
        "Base.CAR15",
        "Base.CAR15D",
        "Base.AssaultRifle2",
        "Base.AssaultRifle",
        "Base.HuntingRifle",
        "Base.VarmintRifle",
        "Base.LeverRifle",
        "Base.MP5",
        "Base.MP5SD",
        "Base.Tec9",
        "Base.Pistol2",
        "Base.Pistol",
        "Base.Glock",
        "Base.Revolver_Short",
        "Base.Revolver_Long",
        "Base.Pistol3",
        "Base.Revolver",
        "Base.P229",
        "Base.Mosin",
        "Base.Saiga12",
        "Base.SVD",
        "Base.Galil",
        "Base.UMP45",
        "Base.Makarov",
        "Base.USP45",
        "Base.SV98",
        "Base.M249",
        "Base.PKM",
        "Base.Vityaz",
        "Base.HK416",
        "Base.VSS",
        "Base.SVT40",
        "Base.MP153",
        "Base.MP153sawn",
    },

    Tool = {
        "Base.FireKlean",
        "Base.CleaningKit",
        "Base.OilFilter",
        "Base.OilFilter2",
    },

    WepAmmoMag = {
        "Base.762Clip",
        "Base.223Clip20",
        "Base.22ClipRifle",
        "Base.308Clip",
        "Base.9mmClip20",
        "Base.9mmClip17",
        "Base.9mmClip30",
        "Base.9mmClip13",
        "Base.762Clip10",
        "Base.939Clip10",
        "Base.556box100",
        "Base.762box100",
        "Base.12Clip5",
        "Base.762Clip102",
        "Base.762Clip103",
        "Base.9mmClip8",
        "Base.45Clip12",
        "Base.45Clip25",
        "Base.9mmClip302",
    },

    Ammo = {
        "Base.762Box",
        "Base.762Bullets",
        "Base.22Bullets",
        "Base.22Box",
    },

}