return {

    ClothAcc = {
        "Base.Belt3",
        "Base.Belt4",
        "Base.HolsterSimpleL",
        "Base.QuiverB",
        "Base.SwordSheath",
        "Base.ShieldBelt",
        "Base.Toolbelt",
    },

    ClothBag = {
        "Base.FirstAidKitB",
        "Base.AFAKB",
        "Base.ToolBoxB",
        "Base.LunchboxB",
        "Base.Lunchbox2B",
        "Base.PistolCase1B",
        "Base.ScrapLegPouchL",
        "Base.ScrapLegPouchR",
    },

    Cont = {
        "Base.AFAK",
        "Base.HookedWaterBottleEmptyOrange",
        "Base.HookedWaterBottleEmptyYellow",
        "Base.HookedWaterBottleEmptyGreen",
        "Base.HookedWaterBottleEmptyPurple",
        "Base.HookedWaterBottleEmptyRed",
    },

    SurCamp = {
        "Base.TentKitGreen",
    },

    Craft = {
        "Base.HookB",
        "TW.PropaneGasFurnace",
        "TW.GunParts",
        "TW.HugePropaneTank",
        "TW.LargePropaneTank",
        "TW.AirTank",
        "TW.MetalWorkbench",
        "TW.BoxScrews",
        "TW.BoxLargeBolts",
        "TW.LargeBolt",
        "TW.Spring",
        "TW.Chain",
        "TW.Motor",
        "TW.GolfClubHead",
        "TW.HammerHead",
        "TW.SledgeHammerHead",
        "TW.AxeHead",
        "TW.SmallBlade",
        "TW.SmallMetalBar",
        "TW.MeatCleaverHead",
        "TW.ScytheHead",
        "TW.LongBlade",
        "TW.ShovelHead",
        "TW.HoeHead",
        "TW.PickaxeHead",
        "TW.RakeHead",
        "TW.ForkHead",
    },

    FoodB = {
        "Base.HookedWaterBottleFullOrange",
        "Base.HookedWaterBottleFullYellow",
        "Base.HookedWaterBottleFullGreen",
        "Base.HookedWaterBottleFullPurple",
        "Base.HookedWaterBottleFullRed",
    },

    Elec = {
        "Radio.CDplayer",
    },

    ClothBack = {
        "Base.Rucksack",
    },

    LitR = {
        "SArmor.ArmorMag1",
        "SArmor.ArmorMag2",
        "SArmor.ArmorMag3",
        "SArmor.ArmorMag4",
        "SArmor.ArmorMag5",
        "SGuns.ScrapGunMag1",
        "SGuns.ScrapGunMag2",
        "SGuns.ScrapGunMag3",
        "SGuns.ScrapGunMag4",
        "SWeapons.WeaponMag1",
        "SWeapons.WeaponMag2",
        "SWeapons.WeaponMag3",
        "SWeapons.WeaponMag4",
        "SWeapons.WeaponMag5",
        "SWeapons.WeaponMag6",
        "TW.WorkshopMag1",
        "TW.WorkshopMag2",
        "TW.WorkshopMag3",
        "TW.WorkshopMag4",
        "TW.WorkshopMag5",
    },

    WepShield = {
        "Base.ScrapShield",
        "Base.WoodenShield",
        "Base.ScrapShieldPainted1",
        "Base.ScrapShieldPainted2",
        "Base.ScrapShieldPainted3",
        "Base.CarDoorShield",
        "Base.CarDoorShield1",
        "Base.CarDoorShield2",
    },

    ClothArm = {
        "Base.ScrapHandPlate2R",
        "Base.ScrapHandPlate2L",
        "Base.ScrapHandPlateR",
        "Base.ScrapHandPlateL",
        "Base.ScrapHandPlateStuddedR",
        "Base.ScrapHandPlateStuddedL",
        "Base.ScrapPauldrons",
        "Base.ScrapPauldrons2",
        "Base.ScrapPauldrons2Studded",
        "Base.ScrapShoulderPadL",
        "Base.ScrapShoulderPadR",
        "Base.ScrapShoulderPadSawL",
        "Base.ScrapShoulderPadSawR",
        "Base.ScrapShoulderPadBoltsL",
        "Base.ScrapShoulderPadBoltsR",
        "Base.ScrapShoulderPadSignL",
        "Base.ScrapShoulderPadSignR",
    },

    ClothHead = {
        "Base.Hat_ScrapKettleHelmet",
        "Base.Hat_ScrapHelmet",
        "Base.Hat_ScrapHelmetopen",
        "Base.Hat_MotorcycleHelmet2",
        "Base.Hat_WelderMask2",
        "Base.Hat_MotorcycleHelmet2open",
        "Base.Hat_Rebreather",
    },

    ClothLeg = {
        "Base.ScrapKiltSign",
        "Base.ScrapKiltPlated",
        "Base.ScrapKiltStudded",
        "Base.ScrapKilt",
        "Base.ScrapLegPadL",
        "Base.ScrapLegPadR",
        "Base.ScrapLegPadBoltsL",
        "Base.ScrapLegPadBoltsR",
        "Base.ScrapLegPadSign2L",
        "Base.ScrapLegPadSign2R",
        "Base.ScrapLegPadSignL",
        "Base.ScrapLegPadSignR",
        "Base.ScrapShinPlateR",
        "Base.ScrapShinPlateL",
        "Base.ScrapShinPlateStuddedR",
        "Base.ScrapShinPlateStuddedL",
        "Base.ScrapShinPlate2R",
        "Base.ScrapShinPlate2L",
    },

    ClothBody = {
        "Base.ScrapVest",
        "Base.ScrapVestPlated",
        "Base.ScrapVestSign",
        "Base.ScrapVestStudded",
    },

    Ammo = {
        "SGuns.SSBox",
        "SGuns.MetalScraps",
        "SGuns.ShrapnelShell",
        "SGuns.SBBox",
        "SGuns.SBullets",
        "SGuns.ScrapBullets",
        "SGuns.ScrapBBox",
    },

    WepAmmoMag = {
        "SGuns.HRMagazine",
        "SGuns.SSMGMagazine",
        "SGuns.ScrapSMGMagazine",
        "SGuns.ScrapPistolMagazine",
        "SGuns.GatlingBoxMagazine",
    },

    WepFire = {
        "SGuns.HPS",
        "SGuns.HP",
        "SGuns.HDBS",
        "SGuns.HR",
        "SGuns.HRB",
        "SGuns.SlamFire",
        "SGuns.SARBO",
        "SGuns.SSMGUnfolded",
        "SGuns.SSMGFolded",
        "SGuns.SAR",
        "SGuns.SARB",
        "SGuns.SSR",
        "SGuns.ScrapPistol",
        "SGuns.ScrapSMG",
        "SGuns.ScrapGatling",
    },

    WepBomb = {
        "SGuns.NailBomb",
        "SGuns.GlassBomb",
        "SGuns.HPB",
        "SGuns.HD",
    },

    WepRange = {
        "SGuns.TBottle",
    },

    WepMelee = {
        "SWeapons.2x4",
        "SWeapons.2x4Can",
        "SWeapons.2x4Nail",
        "SWeapons.2x4Bolt",
        "SWeapons.2x4Scissors",
        "SWeapons.2x4Screwdriver",
        "SWeapons.2x4SScrewdriver",
        "SWeapons.ScrapPickaxe",
        "SWeapons.BigScrapPickaxe",
        "SWeapons.PipewithScissors",
        "SWeapons.TireIronAxe",
        "SWeapons.SalvagedPipeWrench",
        "SWeapons.SalvagedClimbingAxe",
        "SWeapons.SharpenedStopSign",
        "SWeapons.HugeScrapPickaxe",
        "SWeapons.SalvagedCrowbar",
        "SWeapons.BoltBat",
        "SWeapons.ChainBat",
        "SWeapons.SalvagedPipe",
        "SWeapons.TinCanClub",
        "SWeapons.SalvagedSledgehammer",
        "SWeapons.GearMace",
        "SWeapons.WireBat",
        "SWeapons.Micromaul",
        "SWeapons.ScrapSword",
        "SWeapons.ScrapMachete",
        "SWeapons.SalvagedNightstick",
        "SWeapons.SalvagedMachete",
        "SWeapons.ScrapBlade",
        "SWeapons.SalvagedBlade",
        "SWeapons.SalvagedCleaver",
        "SWeapons.SharpenedScrewdriver",
        "SWeapons.GlassShiv",
        "SWeapons.ScrapShiv",
        "SWeapons.SalvagedShiv",
        "SWeapons.SalvagedShivO",
        "SWeapons.ScrapClub",
        "SWeapons.SalvagedClub",
        "SWeapons.SpearSharpenedScrewdriver",
        "SWeapons.SpearScrapShiv",
        "SWeapons.SpearScrapMachete",
        "SWeapons.SpearSalvaged",
        "SWeapons.ScrapSpear",
    },

    Tool = {
        "Base.NailGun",
        "Base.NailGunMagazine",
        "Base.CordlessDrill",
        "TW.File",
        "TW.Pliers",
        "TW.MetalCutter",
    },

    CraftMetal = {
        "TW.MetalPipeMold",
        "TW.MetalBarMold",
        "TW.SmallMetalSheetMold",
        "TW.MetalParts",
        "Base.LeadPipe",
    },

}