return {

    Ammo = {
        "Base.132Box",
        "Base.132Bullets",
        "Base.40Clip",
        "Base.40Rounds",
        "Base.500Box",
        "Base.500Bullets",
        "Base.LewisDrum",
        "Base.MASClip",
        "Base.PPSHClip",
        "Base.WitchySMGClip",
        "Base.40ClipCan",
        "Base.VulcanClip",
        "Base.556HMGBelt",
    },

    ClothHead = {
        "Base.Animask1",
        "Base.Animask12",
        "Base.Animask13",
        "Base.Animask2",
        "Base.Animask22",
        "Base.BalaTight",
        "Base.BalaTight2",
        "Base.FlatCap",
        "Base.GlassesPLL",
        "Base.GlassesPLLR",
        "Base.Hat_Altyn",
        "Base.Hat_Altynopen",
        "Base.HATELA",
        "Base.HATELAHEADS",
        "Base.RogueMask",
        "Base.Mask_HECU",
        "Base.Hat_WitchyHat",
        "Base.Hat_TubaHat",
        "Base.ClericMask",
        "Base.Hat_Tknight",
        "Base.Hat_Tknightopen",
        "Base.Hat_SpiffoEars",
        "Base.Animask23",
    },

    ClothBack = {
        "Base.Bag_ParaMedic",
        "Base.smallback",
    },

    ClothArm = {
        "Base.bandagesgloves",
        "Base.bandagesglovesdenim",
        "Base.bandagesglovesleather",
        "Base.ElbowbandL",
        "Base.ElbowbandR",
        "Base.Gloves_Rogue",
        "Base.RogueArms",
        "Base.KnightArms",
        "Base.TKSPad",
        "Base.Gloves_TKnight",
    },

    ClothLeg = {
        "Base.bandageslegs",
        "Base.bandageslegsdenim",
        "Base.bandageslegsleather",
        "Base.ClericPants",
        "Base.Leggings_Bottoms",
        "Base.PFKnee",
        "Base.PFPants",
        "Base.PFShorts",
        "Base.RogueGreaves",
        "Base.ShorterDenim",
        "Base.Shorts_Kimo",
        "Base.KnightGreaves",
    },

    ClothBag = {
        "Base.BeltRig",
        "Base.medbag",
        "Base.medbag2",
        "Base.MVest",
        "Base.MVest2",
        "Base.RogueWaistBag",
        "Base.TacticalWaistBagBack",
        "Base.TacticalWaistBagBackMed",
        "Base.TacticalWaistBagFront",
        "Base.TacticalWaistBagFrontMed",
        "Base.MVest_Black",
        "Base.MVest2_Black",
        "Base.MVest_Military",
        "Base.MVest2_Military",
        "Base.TacticalWaistBagBack_Black",
        "Base.TacticalWaistBagFront_Black",
        "Base.TacticalWaistBagBack_Military",
        "Base.TacticalWaistBagFront_Military",
        "Base.RogueWaistBag_Black",
        "Base.RogueWaistBag_Military",
    },

    WepMelee = {
        "Base.ClericMace",
        "Base.RogueSword",
        "Base.RogueSword2",
        "Base.TKSword",
        "Base.TKSword2",
        "Base.TKSwordHalf",
        "Base.Tanto",
        "Base.Tanto2",
        "Base.Tanto3",
        "Base.WitchyStaff",
    },

    ClothAcc = {
        "Base.ClericNeck",
        "Base.HolsterPLL",
        "Base.HolsterPLL2",
        "Base.HolsterPLL2M",
        "Base.HolsterPLLLEFT",
        "Base.HolsterPLLLEFT2",
        "Base.HolsterPLLLEFT2M",
        "Base.HolsterPLLLEFTM",
        "Base.HolsterPLLM",
        "Base.RogueWaist",
        "Base.KnightWaist",
        "Base.strapchest_Black",
        "Base.strapchest2_Black",
        "Base.strapchest_Military",
        "Base.strapchest2_Military",
    },

    WepFire = {
        "Base.ClericRevolver",
        "Base.JERICHOP",
        "Base.Lewis",
        "Base.m32r",
        "Base.m79",
        "Base.m79A",
        "Base.MAS38",
        "Base.p88p",
        "Base.PPSH",
        "Base.RogueSniperRifle",
        "Base.TKShotgun",
        "Base.WitchySMG",
        "Base.WitchySMGE",
        "Base.WitchySMGEN",
        "Base.WitchySMGN",
        "Base.AutoCannon",
        "Base.AutoCannonA",
        "Base.MP5GL",
        "Base.MP5GL2",
        "Base.Vulcan",
    },

    ClothBody = {
        "Base.CropTop",
        "Base.PFCropped",
        "Base.PFVest",
        "Base.PFVest2",
        "Base.RogueHoodie",
        "Base.SpookySuit",
        "Base.SportTankTop",
        "Base.strapchest",
        "Base.strapchest2",
        "Base.Vest_RogueVest",
        "Base.Vest_WitchyCarrier",
        "Base.WetSuit",
        "Base.Vest_HECU",
        "Base.WitchyDress",
        "Base.ChainMail",
        "Base.Vest_Tknight",
        "Base.aresbody",
        "Base.Vest_RogueVest_Black",
        "Base.Vest_RogueVest_Military",
        "Base.Vest_WitchyCarrier_Military",
        "Base.Vest_WitchyCarrier_Black",
    },

    Appear = {
        "Base.Hat_HairBun2",
        "Base.Hat_HairCroft",
        "Base.Hat_HairFab",
        "Base.Hat_HairFio",
        "Base.Hat_HairFio2",
        "Base.Hat_HairLeo",
        "Base.Hat_HairMarcel",
        "Base.Hat_HairP",
        "Base.Hat_HairPiggy",
        "Base.Hat_HairRachel2",
        "Base.Hat_HairWendy",
        "Base.Hat_HairWide",
    },

    ClothFeet = {
        "Base.Shoes_Canvasshoes",
        "Base.Shoes_CanvasshoesLong",
        "Base.Shoes_Rogue",
        "Base.WitchySocks",
        "Base.Shoes_TKnight",
    },

    WepShield = {
        "Base.MShield",
    },

    LitE = {
        "Base.Grimoire",
        "Base.grimoireclosed",
    },

}