return {

    FoodP = {
        "RuggedRecipes.Cucumber",
        "RuggedRecipes.HoochMash",
        "RuggedRecipes.FermentingHoochMash",
        "RuggedRecipes.FermentingBerryWine",
        "RuggedRecipes.FermentingKvass",
        "RuggedRecipes.UndriedBeefJerky",
        "RuggedRecipes.UndriedSmokedFish",
        "RuggedRecipes.UndriedBiltong",
        "RuggedRecipes.FermentingKentuckyKimchi",
        "RuggedRecipes.FermentedKentuckyKimchi",
        "RuggedRecipes.FermentedKentuckyKimchiOpen",
        "RuggedRecipes.KentuckyKimchiBowl",
        "RuggedRecipes.JarredPicklesUnready",
        "RuggedRecipes.JarredPicklesReady",
        "RuggedRecipes.CannedCucumber",
        "RuggedRecipes.JarredSauerkrautUnready",
        "RuggedRecipes.JarredSauerkrautOpen",
        "RuggedRecipes.SauerkrautBowl",
        "RuggedRecipes.PreparedApple",
        "RuggedRecipes.DriedApple",
        "RuggedRecipes.PreparedBanana",
        "RuggedRecipes.DriedBanana",
        "RuggedRecipes.PreparedCherry",
        "RuggedRecipes.DriedCherry",
        "RuggedRecipes.PreparedGrapefruit",
        "RuggedRecipes.DriedGrapefruit",
        "RuggedRecipes.PreparedGrapes",
        "RuggedRecipes.DriedGrapes",
        "RuggedRecipes.PreparedLemon",
        "RuggedRecipes.DriedLemon",
        "RuggedRecipes.PreparedMango",
        "RuggedRecipes.DriedMango",
        "RuggedRecipes.PreparedOrange",
        "RuggedRecipes.DriedOrange",
        "RuggedRecipes.PreparedPeach",
        "RuggedRecipes.DriedPeach",
        "RuggedRecipes.PreparedPineapple",
        "RuggedRecipes.DriedPineapple",
        "RuggedRecipes.PreparedStrawberries",
        "RuggedRecipes.DriedStrawberries",
        "RuggedRecipes.PreparedWatermelon",
        "RuggedRecipes.DriedWatermelon",
        "RuggedRecipes.PreparedPear",
        "RuggedRecipes.DriedPear",
        "RuggedRecipes.PreparedLime",
        "RuggedRecipes.DriedLime",
        "RuggedRecipes.BakedPotato",
        "RuggedRecipes.PreppedTater",
    },

    FoodN = {
        "RuggedRecipes.ReadyHoochMash",
        "RuggedRecipes.ReadyBerryWine",
        "RuggedRecipes.ReadyKvass",
        "RuggedRecipes.SmokedFish",
        "RuggedRecipes.Biltong",
        "RuggedRecipes.JarredSauerkrautReady",
    },

    FoodA = {
        "RuggedRecipes.Hooch",
        "RuggedRecipes.BerryWine",
        "RuggedRecipes.Kvass",
    },

    LitR = {
        "RuggedRecipes.RuggedRecipesMagazine1",
        "RuggedRecipes.RuggedRecipesMagazine2",
        "RuggedRecipes.RuggedRecipesMagazine3",
        "RuggedRecipes.RuggedRecipesMagazine4",
    },

}