return {

    LitR = {
        "LabBooks.BkLaboratoryEquipment1",
        "LabBooks.BkVirologyCourses1",
        "LabBooks.BkChemistryCourse",
    },

    Tool = {
        "LabItems.LabMicroscope",
        "LabItems.LabChromatograph",
        "LabItems.LabSpectrometer",
        "LabItems.LabChemistrySet",
        "LabItems.LabCentrifuge",
        "LabItems.LabMuffleFurnace",
        "LabItems.LabWorkbench",
        "LabItems.LabEasel",
        "LabItems.LabDecorSkeleton",
        "LabItems.LabDecorVirusModel",
        "LabItems.LabDecorCaduceus",
        "LabItems.LabDecorWhiteboard",
        "LabItems.LabPosterPeriodicTable",
        "LabItems.LabPosterSexyNurse",
        "LabItems.LabPosterWashHands",
        "LabItems.LabPosterBiohazard",
        "LabItems.LabPosterHumanBrain",
        "LabItems.LabNeonSignPharmacy",
        "LabItems.LabNeonSignPizza",
        "LabItems.Mov_Morge1",
        "LabItems.Mov_Morge2",
        "LabItems.LabSyringe",
        "LabItems.LabSyringeReusable",
        "LabItems.LabSyringeReusableUsed",
        "LabItems.LabSyringePack",
        "LabItems.LabSyringeUsed",
        "LabItems.LabTestTube",
        "LabItems.LabTestTubeDirty",
        "LabItems.LabFlask",
        "LabItems.LabFlaskWater",
        "LabItems.LabFlaskDirty",
        "LabItems.LabTestResultNegative",
        "LabItems.LabTestResultPositive",
        "LabItems.LabGarbageBagWithRemains",
        "LabItems.LabPlasticBagWithRemains",
        "LabItems.CmpChlorineTablets",
    },

    Craft = {
        "LabItems.MatInfectedBlood",
        "LabItems.MatTaintedBlood",
        "LabItems.MatShatteredGlass",
        "LabItems.ChHydrochloricAcidCan",
        "LabItems.ChSodiumHydroxideBag",
        "LabItems.ChAmmonia",
        "LabItems.ChSulfuricAcidCan",
        "LabItems.CmpSyringeWithBlood",
        "LabItems.CmpSyringeReusableWithBlood",
        "LabItems.CmpSyringeWithTaintedBlood",
        "LabItems.CmpSyringeReusableWithTaintedBlood",
        "LabItems.CmpTestTubeWithInfectedBlood",
        "LabItems.CmpTestTubeWithTaintedBlood",
        "LabItems.CmpFlaskWithBloodCells",
        "LabItems.CmpFlaskWithBloodPlasma",
        "LabItems.CmpFlaskWithLeukocytes",
        "LabItems.CmpTestTubeWithAntibodies",
        "LabItems.CmpFlaskWithSodiumHypochlorite",
        "LabItems.CmpFlaskWithAmmoniumSulfate",
        "LabItems.CmpFlaskWithHydrogenPeroxide",
        "LabItems.FrnIngotMold",
        "LabItems.FrnGolgNugget",
        "LabItems.FrnSilverNugget",
        "LabItems.FrnGolgIngot",
        "LabItems.FrnSilverIngot",
    },

    Med = {
        "LabItems.CmpSyringeWithPlainVaccine",
        "LabItems.CmpSyringeReusableWithPlainVaccine",
        "LabItems.CmpSyringeWithQualityVaccine",
        "LabItems.CmpSyringeReusableWithQualityVaccine",
        "LabItems.CmpSyringeWithAdvancedVaccine",
        "LabItems.CmpSyringeReusableWithAdvancedVaccine",
        "LabItems.CmpSyringeWithCure",
        "LabItems.CmpSyringeReusableWithCure",
        "LabItems.CmpAlbuminPills",
    },

}