return {

    ClothBack = {
        "Base.Bag_cat_1",
        "Base.Bag_cat_2",
        "Base.Bag_cat_3",
        "Base.Bag_cat_4",
        "Base.Bag_cat_5",
        "Base.Bag_cat_6",
    },

    ClothBag = {
        "Base.bbao1",
        "Base.bbbao1",
        "Base.bpbao1",
        "Base.pbao1",
    },

    ClothBody = {
        "Base.beike_cat1",
        "Base.bra_cat12",
        "Base.bra_cat12G",
        "Base.bra_cat19",
        "Base.bra_cat19_1",
        "Base.clothes_cat1",
        "Base.clothes_cat10",
        "Base.clothes_cat10_G",
        "Base.clothes_cat11",
        "Base.clothes_cat12",
        "Base.clothes_cat12G",
        "Base.clothes_cat13",
        "Base.clothes_cat14",
        "Base.clothes_cat14_1",
        "Base.clothes_cat15",
        "Base.clothes_cat16",
        "Base.clothes_cat16_1",
        "Base.clothes_cat16_2",
        "Base.clothes_cat17",
        "Base.clothes_cat18",
        "Base.clothes_cat2",
        "Base.clothes_cat20",
        "Base.clothes_cat20_1",
        "Base.clothes_cat21",
        "Base.clothes_cat22",
        "Base.clothes_cat23",
        "Base.clothes_cat24",
        "Base.clothes_cat25",
        "Base.clothes_cat26",
        "Base.clothes_cat27",
        "Base.clothes_cat28",
        "Base.clothes_cat29",
        "Base.clothes_cat3",
        "Base.clothes_cat4",
        "Base.clothes_cat5",
        "Base.clothes_cat6",
        "Base.clothes_cat7",
        "Base.clothes_cat8",
        "Base.clothes_cat9",
        "Base.clothes_catM",
        "Base.clothes_catMb",
        "Base.clothes_picao_cat",
        "Base.picao_cat",
        "Base.XXhong",
    },

    ClothLeg = {
        "Base.beike_cat2",
        "Base.pant_cat1",
        "Base.pant_cat11",
        "Base.pant_cat11_w",
        "Base.pant_cat12",
        "Base.pant_cat12G",
        "Base.pant_cat15",
        "Base.pant_cat15_h",
        "Base.pant_cat16",
        "Base.pant_cat16_1",
        "Base.pant_cat18",
        "Base.pant_cat19",
        "Base.pant_cat2",
        "Base.pant_cat22",
        "Base.pant_cat24",
        "Base.pant_cat25",
        "Base.pant_cat26",
        "Base.pant_cat28",
        "Base.pant_cat29",
        "Base.pant_cat3",
        "Base.pant_cat4",
        "Base.pant_cat6",
        "Base.pant_cat7",
        "Base.pant_cat9",
    },

    ClothAcc = {
        "Base.belt_cat1",
        "Base.belt_cat19",
        "Base.belt_cat24",
        "Base.belt_cat28",
        "Base.belt_cat6",
        "Base.belt_catgun",
        "Base.neck_cat17",
        "Base.neck_cat22",
        "Base.neck_cat25",
    },

    Misc = {
        "Base.CompleteSoulGem",
        "Base.Gold_Coin",
        "Base.Golden_sand",
    },

    ClothFeet = {
        "Base.gaogen_cat1",
        "Base.shoe_cat1",
        "Base.shoe_cat10",
        "Base.shoe_cat11",
        "Base.shoe_cat12",
        "Base.shoe_cat14",
        "Base.shoe_cat15",
        "Base.shoe_cat16",
        "Base.shoe_cat17",
        "Base.shoe_cat18",
        "Base.shoe_cat19",
        "Base.shoe_cat2",
        "Base.shoe_cat20",
        "Base.shoe_cat24",
        "Base.shoe_cat28",
        "Base.shoe_cat29",
        "Base.shoe_cat4",
        "Base.shoe_cat5",
        "Base.shoe_cat6",
    },

    ClothArm = {
        "Base.glove_cat10",
        "Base.glove_cat11_w",
        "Base.glove_cat18",
        "Base.glove_cat19",
        "Base.glove_cat2",
        "Base.glove_cat20",
        "Base.glove_cat28",
    },

    ClothHead = {
        "Base.hat_cat_1",
        "Base.hat_cat_17",
        "Base.hat_cat_2",
        "Base.hat_cat_28",
        "Base.hat_cat_3",
        "Base.head_cat11",
        "Base.head_cat5",
        "Base.head_cat6",
        "Base.head_junyong",
        "Base.headcat1",
        "Base.Mask_cat13",
    },

    ClothMisc = {
        "Base.JumpEggs",
        "Base.JumpEggs2",
        "Base.RuBag",
        "Base.RuBag1",
    },

    WepMelee = {
        "Base.Knife_cat",
    },

    Junk = {
        "Base.kuoyin",
    },

    FoodN = {
        "Base.Maggots",
        "Base.Maggots2",
    },

    ClothUnder = {
        "Base.neiku_cat16",
        "Base.neiku_cat19",
        "Base.rutie20",
    },

}