return {

    Med = {
        "iMeds.BloodPressureMonitorLeft",
        "iMeds.BloodPressureMonitorRight",
        "iMeds.HeartRateMonitorLeft",
        "iMeds.HeartRateMonitorRight",
        "iMeds.EmptyBloodBag",
        "iMeds.FullBloodBag",
        "iMeds.PeripheralVenousCatheter",
        "iMeds.BloodTestingKit",
        "iMeds.ErythrocyteSuspensionBagABN",
        "iMeds.ErythrocyteSuspensionBagABP",
        "iMeds.ErythrocyteSuspensionBagAN",
        "iMeds.ErythrocyteSuspensionBagAP",
        "iMeds.ErythrocyteSuspensionBagBN",
        "iMeds.ErythrocyteSuspensionBagBP",
        "iMeds.ErythrocyteSuspensionBagON",
        "iMeds.ErythrocyteSuspensionBagOP",
        "iMeds.PlasmaBagABN",
        "iMeds.PlasmaBagABP",
        "iMeds.PlasmaBagAN",
        "iMeds.PlasmaBagAP",
        "iMeds.PlasmaBagBN",
        "iMeds.PlasmaBagBP",
        "iMeds.PlasmaBagON",
        "iMeds.PlasmaBagOP",
        "iMeds.Stethoscope",
        "iMeds.BloodTester",
        "iMeds.BloodVolumeIncreaser",
        "iMeds.BloodVolumeReducer",
        "iMeds.DrugApplier",
        "iMeds.PulseChecker",
        "iMeds.SyringePack",
        "iMeds.Syringe",
        "iMeds.NeedlePack",
        "iMeds.Needle",
        "iMeds.SyringeWithNeedle",
        "iMeds.FullSyringeWithNeedle",
    },

    Drugs = {
        "iMeds.Alkagin",
        "iMeds.AlkaginPack",
        "iMeds.BismuthSubsalicylate",
        "iMeds.BismuthSubsalicylatePack",
        "iMeds.Butamirate",
        "iMeds.ButamiratePack",
        "iMeds.Erythropoietin",
        "iMeds.ErythropoietinPack",
        "iMeds.HemoStop",
        "iMeds.HemoStopPack",
        "iMeds.Morphine",
        "iMeds.MorphinePack",
        "iMeds.Naloxon",
        "iMeds.NaloxonPack",
        "iMeds.Nasivion",
        "iMeds.NasivionPack",
        "iMeds.Umifenovir",
        "iMeds.UmifenovirPack",
        "iMeds.UnknownPack",
    },

}