return {

    Drugs = {
        "SM.SMPack",
        "SM.SMPackLight",
        "SM.SMPackGold",
        "SM.SMPackMenthol",
        "SM.SMCartonCigarettes",
        "SM.SMCartonCigarettesLight",
        "SM.SMCartonCigarettesGold",
        "SM.SMCartonCigarettesMenthol",
        "SM.SMFullPack",
        "SM.SMFullPackLight",
        "SM.SMFullPackGold",
        "SM.SMFullPackMenthol",
        "SM.SMCigarette",
        "SM.SMCigaretteLight",
        "SM.SMPCigaretteGold",
        "SM.SMPCigaretteMenthol",
        "SM.SMButt",
        "SM.SMButt2",
        "SM.SMHomemadeCigarette",
        "SM.SMHomemadeCigarette2",
        "SM.SMGum",
        "SM.SMNicorette",
        "SM.SMNicoretteBox",
        "SM.SMSmokingDeviceWithPinchTobacco",
        "SM.SMSmokingDeviceWithSmokingBlend",
        "SM.SMSmokingBlendBong",
        "SM.SMSmokingBlendPipe",
    },

    Junk = {
        "SM.Ashtray",
        "SM.EmptyMatchbox",
        "SM.CarbonizedFilter",
        "SM.SMEmptyPack",
        "SM.SMEmptyPackGold",
        "SM.SMEmptyPackLight",
        "SM.SMEmptyPackMenthol",
        "SM.ChocolateFoil",
    },

    Tool = {
        "SM.Lighter",
        "SM.Matches",
        "SM.SMEmptyLighter",
    },

    Craft = {
        "SM.SMFilter",
        "SM.SMFoil",
        "SM.SMUsedFoilLighter",
        "SM.SMCrumpledWithFoilCap",
        "SM.SMCrumpledWithFoilCap2",
        "SM.SMCrumpledBottle",
        "SM.SMCrumpledBottle2",
        "SM.SMTobaccoPouches",
        "SM.SMPinchTobacco",
        "SM.SMSmallHandfulTobacco",
        "SM.SMHandfulTobacco",
        "SM.SMPileTobacco",
        "SM.SMBigPileTobacco",
        "SM.SMSmokingBlend",
    },

}