return {

    Drugs = {
        "Cigs.CigsCigaretteReg",
        "Cigs.CigsButtReg",
        "Cigs.CigsFilterReg",
        "Cigs.CigsOpenPackReg",
        "Cigs.CigsClosedPackReg",
        "Cigs.CigsEmptyPackReg",
        "Cigs.CigsCartonReg",
        "Cigs.CigsCartonRegEmpty",
        "Cigs.CigsCaseReg",
        "Cigs.CigsSpawnPackLite",
        "Cigs.CigsCigaretteLite",
        "Cigs.CigsButtLite",
        "Cigs.CigsFilterLite",
        "Cigs.CigsOpenPackLite",
        "Cigs.CigsClosedPackLite",
        "Cigs.CigsEmptyPackLite",
        "Cigs.CigsCartonLite",
        "Cigs.CigsCartonLiteEmpty",
        "Cigs.CigsCaseLite",
        "Cigs.CigsSpawnPackMent",
        "Cigs.CigsCigaretteMent",
        "Cigs.CigsButtMent",
        "Cigs.CigsFilterMent",
        "Cigs.CigsOpenPackMent",
        "Cigs.CigsClosedPackMent",
        "Cigs.CigsEmptyPackMent",
        "Cigs.CigsCartonMent",
        "Cigs.CigsCartonMentEmpty",
        "Cigs.CigsCaseMent",
        "Cigs.CigsSpawnPackGold",
        "Cigs.CigsCigaretteGold",
        "Cigs.CigsButtGold",
        "Cigs.CigsFilterGold",
        "Cigs.CigsOpenPackGold",
        "Cigs.CigsClosedPackGold",
        "Cigs.CigsEmptyPackGold",
        "Cigs.CigsCartonGold",
        "Cigs.CigsCartonGoldEmpty",
        "Cigs.CigsCaseGold",
        "Cigs.CardboardBox",
        "Greenfire.GFCigaretteCarton",
        "Greenfire.GFEmptyCigaretteCarton",
        "Greenfire.GFUsedCigaretteCarton",
        "Greenfire.Cannabis",
        "Greenfire.Tobacco",
        "Greenfire.Bong",
        "Greenfire.SmokingPipe",
        "Greenfire.RollingPapers",
        "Greenfire.PipeTobaccoBag",
        "Greenfire.SBrownieBatter",
        "Greenfire.SBrowniePan",
        "Greenfire.SBrownie",
        "Greenfire.SCrispyMix",
        "Greenfire.SCrispySauce",
        "Greenfire.NiceCrispiezPan",
        "Greenfire.NiceCrispiez",
        "Greenfire.FreshBTobacco",
        "Greenfire.DryBTobacco",
        "Greenfire.GFCigarettes",
        "Greenfire.GFCigarette",
        "Greenfire.BluntCigar",
        "Greenfire.HalfBluntCigar",
        "Greenfire.BluntWrap",
        "Greenfire.UncuredCigar",
        "Greenfire.CigarLeaf",
        "Greenfire.GFCigar",
        "Greenfire.HalfCigar",
        "Greenfire.GFCigaretteCase",
        "Greenfire.TobaccoBong",
        "Greenfire.TobaccoPipe",
    },

    SurFarm = {
        "Greenfire.CannabisSeed",
        "Greenfire.TobaccoSeed",
        "Greenfire.CannabisBagSeed",
        "Greenfire.TobaccoBagSeed",
    },

    FoodN = {
        "Greenfire.Marshmallows",
    },

}