return {

    FoodB = {
        "nuka.NukaCherry",
        "nuka.NukaCherryOpen",
        "nuka.NukaCherryWater",
        "nuka.NukaCola",
        "nuka.NukaColaOpen",
        "nuka.NukaColaWater",
        "nuka.NukaCranberry",
        "nuka.NukaCranberryOpen",
        "nuka.NukaCranberryWater",
        "nuka.NukaDark",
        "nuka.NukaDarkOpen",
        "nuka.NukaDarkWater",
        "nuka.NukaGrape",
        "nuka.NukaGrapeOpen",
        "nuka.NukaGrapeWater",
        "nuka.NukaOrange",
        "nuka.NukaOrangeOpen",
        "nuka.NukaOrangeWater",
        "nuka.NukaQuantum",
        "nuka.NukaQuantumOpen",
        "nuka.NukaQuantumWater",
        "nuka.NukaQuartz",
        "nuka.NukaQuartzOpen",
        "nuka.NukaQuartzWater",
        "nuka.NukaShine",
        "nuka.NukaShineOpen",
        "nuka.NukaShineWater",
        "nuka.NukaVictory",
        "nuka.NukaVictoryOpen",
        "nuka.NukaVictoryWater",
        "nuka.NukaWild",
        "nuka.NukaWildOpen",
        "nuka.NukaWildWater",
    },

    Cont = {
        "nuka.EmptyNukaCherry",
        "nuka.EmptyNukaCola",
        "nuka.EmptyNukaCranberry",
        "nuka.EmptyNukaDark",
        "nuka.EmptyNukaGrape",
        "nuka.EmptyNukaOrange",
        "nuka.EmptyNukaQuantum",
        "nuka.EmptyNukaQuartz",
        "nuka.NukaShineEmpty",
        "nuka.EmptyNukaVictory",
        "nuka.EmptyNukaWild",
    },

    Junk = {
        "nuka.NukaCherryCap",
        "nuka.NukaColaCap",
        "nuka.NukaCranberryCap",
        "nuka.NukaDarkCap",
        "nuka.NukaGrapeCap",
        "nuka.NukaOrangeCap",
        "nuka.NukaQuantumCap",
        "nuka.NukaQuartzCap",
        "nuka.NukaVictoryCap",
        "nuka.NukaWildCap",
    },

}