return {

    LitR = {
        "FMJ.LockPickingMag",
        "FMJ.LockPickingMag2",
        "Base.DairyCookingMag",
    },

    Tool = {
        "FMJ.BobbyPin",
        "FMJ.BobbyPinRaw",
    },

    Cook = {
        "Base.Strainer",
        "RS.MetalBowl",
    },

    FoodN = {
        "Base.PowderedMilk",
        "Base.YogurtCulture",
        "Base.Butter",
        "FMJ.Herbs",
        "FMJ.Nettle",
        "FMJ.WildWheat",
        "FMJ.WheatGrains",
        "GidOrganizedFood.OS6pkCannedSoup",
        "GidOrganizedFood.OS6pkCannedBeans",
        "GidOrganizedFood.OS6pkCannedBolognese",
        "GidOrganizedFood.OS6pkCannedCarrots",
        "GidOrganizedFood.OS6pkCannedChili",
        "GidOrganizedFood.OS6pkCannedCorn",
        "GidOrganizedFood.OS6pkCannedCornedBeef",
        "GidOrganizedFood.OS6pkCannedMushSoup",
        "GidOrganizedFood.OS6pkCannedPeas",
        "GidOrganizedFood.OS6pkCannedPotato",
        "GidOrganizedFood.OS6pkCannedTomato",
        "GidOrganizedFood.OS8pkCannedTuna",
        "GidOrganizedFood.OS4pkSardines",
        "RS.MapleSyrup",
        "RS.CookingOil",
        "RS.BabyFood",
        "RS.BabyFood2",
        "RS.BabyFood3",
        "RS.GreenOlives",
        "RS.Raisins",
        "RS.Almonds",
        "RS.Garlic",
        "RS.Vanila",
        "RS.EnergyBar",
        "RS.ProteinBar",
        "RS.MintGum",
        "RS.BubbleGum",
        "RS.CandyBox",
        "RS.PackageCandy",
        "RS.ChocolateBox",
        "RS.ChocolatePackage",
        "RS.MediumMREPackage",
        "RS.MREPackage",
        "RS.MREBox",
        "RS.MREBox2",
        "RS.CherriesJar",
        "RS.Pepperoni",
        "Base.RosehipsDried",
        "Base.GrapeLeavesDried",
        "Base.VioletsDried",
    },

    FoodP = {
        "Base.MilkJar",
        "Base.MilkWaterBottle",
        "Base.MilkPopBottle",
        "Base.CheesePrep",
        "Base.YogurtPrep",
        "Base.YogurtJar",
        "Base.Yoghurt",
        "FMJ.Dandelions",
        "FMJ.WildCarrots",
        "FMJ.WildCorn",
        "FMJ.WildPotatoes",
        "FMJ.DeadLizard",
        "FMJ.LizardMeat",
        "FMJ.DeadPheasant",
        "FMJ.PheasantMeat",
        "FMJ.DeadSnake",
        "FMJ.SnakeMeat",
        "FMJ.JarWildCarrots",
        "FMJ.JarWildCorn",
        "FMJ.JarWildPotatoes",
        "FMJ.Omelettes",
        "FMJ.PotatoPancakes",
        "FMJ.JarLizard",
        "FMJ.JarPheasant",
        "FMJ.JarSnake",
        "FMJ.JarChicken",
        "FMJ.JarSteak",
        "FMJ.JarFrogMeat",
        "FMJ.JarMeatPatty",
        "FMJ.JarMuttonChop",
        "FMJ.JarPorkChop",
        "FMJ.JarRabbitmeat",
        "FMJ.JarSmallanimalmeat",
        "FMJ.JarSmallbirdmeat",
        "FMJ.JarSalmon",
        "RS.Croissant",
        "RS.CakeSlice2",
        "RS.BdayCakeSlice",
        "RS.BlueberryTartSlice",
        "RS.Ginger",
        "RS.Camomile",
        "RS.Mint",
        "RS.Lavender",
        "RS.Lime",
        "RS.FilledSmallTupperware",
        "RS.FilledMediumTupperware",
        "RS.Cream",
        "Base.StirFryBowl",
        "Base.RoastedVegetablesBowl",
    },

    SurCamp = {
        "FMJ.BirchBark",
    },

    Misc = {
        "FMJ.Tobacco",
        "FMJ.RollUps",
        "FMJ.QRollUps",
    },

    Med = {
        "GidOrganized.OS30pkAntibiotics",
        "GidOrganized.OS12pkAdhesiveBandages",
        "GidOrganized.OS9pkBandages",
        "GidOrganized.OS9pkSterileBandages",
        "GidOrganized.OS12pkCottonBalls",
        "GidOrganized.OS9pkBandagesDirty",
        "GidOrganized.OS50pkPainkillers",
        "GidOrganized.OS50pkVitamins",
        "GidOrganized.OS50pkBetaBlockers",
        "GidOrganized.OS50pkAntidepressants",
        "GidOrganized.OS50pkSleepingPills",
        "GidOrganized.OS4pkDisinfectant",
        "GidOrganized.OS30pkAlcoholWipes",
        "RS.Aloe",
        "RS.AloeCataplasm",
        "Base.CommonMallowDried",
        "Base.LemonGrassDried",
        "Base.BlackSageDried",
        "Base.GinsengDried",
        "Base.PlantainDried",
        "Base.WildGarlicDried",
    },

    FoodB = {
        "GidOrganizedFood.OS6pkPopDiet",
        "GidOrganizedFood.OS6pkPop",
        "GidOrganizedFood.OS6pkFizz",
        "GidOrganizedFood.OS4pkCoffee",
        "GidOrganizedFood.OS24pkWaterBottleFull",
        "RS.WaterGlass",
        "RS.WaterMetalBowl",
        "RS.WaterRockGlass",
        "RS.WaterShotGlass",
        "RS.Rum",
        "RS.WhiteRum",
        "RS.Vodka",
        "RS.Ginebra",
        "RS.TripleSec",
        "RS.DryVermouth",
        "RS.WhiteTequila",
        "RS.Aguaardiente",
        "RS.Beer1",
        "RS.BeerSixPack1",
        "RS.Beer2",
        "RS.BeerSixPack2",
        "RS.Beer3",
        "RS.BeerSixPack3",
        "RS.Beercan1",
        "RS.Beercan2",
        "RS.Beercan3",
        "RS.Beercan4",
        "RS.SodaBottle",
        "RS.WaterSodaBottle",
        "RS.Cachaza",
        "RS.CoffeeLiquor",
        "Base.Teabag_Medicinal",
        "Base.Teabag_Energizing",
        "Base.Teabag_MedicinalDried",
        "Base.Teabag_EnergizingDried",
        "Base.Tea_CommonMallow",
        "Base.Tea_LemonGrass",
        "Base.Tea_BlackSage",
        "Base.Tea_Ginseng",
        "Base.Tea_Medicinal",
        "Base.Tea_Energizing",
    },

    Cont = {
        "GidOrganizedFood.OS12pkWineEmpty",
        "GidOrganizedFood.OS12pkWineEmpty2",
        "GidOrganizedFood.OS8pkWhiskeyEmpty",
        "GidOrganizedFood.OS24pkWaterBottleEmpty",
        "RS.Glass",
        "RS.RockGlass",
        "RS.ShotGlass",
        "RS.BeerBottleEmpty",
        "RS.SodaBottleEmpty",
        "RS.LunchBox",
        "RS.Briefcase",
        "RS.Suitcase",
        "RS.SmallLeatherBag",
    },

    Craft = {
        "GidOrganizedFood.OS4pkDuctTape",
        "RS.GlassPanel",
        "RS.ShardsOfBrokenGlass",
    },

    WepMelee = {
        "RS.KnuckleKnife",
        "RS.PoliceKnife",
        "RS.CombatKnife",
        "RS.Machete",
        "RS.ImprovisedShardOfBrokenGlassWeapon",
        "RS.Wok",
        "RS.ButcherKnife",
        "RS.GardeningScissors",
        "Base.SpearChippedStone",
    },

    Clean = {
        "RS.DishWashingLiquid",
    },

    Junk = {
        "RS.Plate",
        "RS.PileOfPlates",
        "RS.MargaritaGlass",
        "RS.MartiniGlass",
        "RS.WoodenSpoon",
        "RS.CocktailSpoon",
        "RS.Stir",
        "RS.Shaker",
        "RS.BakingMold",
        "RS.CookieMold",
        "RS.Grater",
        "RS.DirtyPlate",
        "RS.SmallGlassBottle",
        "RS.EmptySmallTuperware",
        "RS.EmptyMediumTuperware",
        "RS.Squeezer",
        "RS.BarSqueezer",
        "RS.Strainer",
        "RS.ChoppingBoard",
        "RS.FryingBasket",
        "RS.PizzaTray",
        "RS.BeerCanEmpty",
        "RS.Icecubes",
        "RS.IcecubesMelted",
        "RS.Plasticicebag",
        "RS.PlasticicebagMelted",
        "RS.SoySauce",
        "RS.MilkPowder",
        "RS.MilkPowder2",
        "RS.BabyFormula",
    },

    ClothB = {
        "RS.NormalBackpack",
        "RS.HikingBackpack",
        "RS.AliceBackpack",
        "RS.MolleBackpack",
    },

}