return {

    LitW = {
        "BicPen.BicPen",
    },

    WepMelee = {
        "BicPen.ComicBicPen",
        "BCGRareWeapons.ReinforcedBaseballBat",
        "BCGRareWeapons.VikingAxe",
        "BCGTools.HandHatchet",
        "BCGTools.CheapSurvivalKnife",
        "BCGTools.SurvivalKnife",
        "BCGTools.RancherMachete",
        "BCGTools.KukriMachete",
        "BCGTools.SplittingAxe",
        "BCGTools.SpearSurvivalKnife",
        "BCGTools.SpearCheapSurvivalKnife",
        "MoreTraits.AntiqueAxe",
        "MoreTraits.ObsidianBlade",
        "MoreTraits.Slugger",
        "MoreTraits.PapierMacheSword",
        "MoreTraits.AntiqueSpear",
        "MoreTraits.AntiqueKatana",
        "Base.OverlookFireAxe",
        "Base.BatLeth",
        "Base.MekLeth",
    },

    ClothFeet = {
        "Base.ahzfitnesssocks",
        "MoreTraits.AntiqueBoots",
    },

    ClothArm = {
        "Base.ahzfitnessarms",
    },

    ClothLeg = {
        "Base.ahzfitnesspants",
        "Base.ahzshortpleatedskirt",
        "Base.ahzshortpleatedskirt_close",
        "Base.ahzshortpleatedskirt_t",
        "Base.ahzshortpleatedskirt_t_close",
        "Base.ahzshortpleatedskirt_t_plaid1",
        "Base.ahzshortpleatedskirt_t_plaid1_close",
        "Base.ahzshortpleatedskirt_t_plaid2",
        "Base.ahzshortpleatedskirt_t_plaid2_close",
        "Base.ahzpleatedminiskirt",
        "Base.ahzpleatedminiskirt_t",
        "Base.ahzpleatedminiskirt_t_plaid1",
        "Base.ahzpleatedminiskirt_t_plaid2",
        "Base.Trousers_PoliceRiotfbilg",
        "Base.Marpat_Pants_w",
        "Base.Marpat_Pants_d",
    },

    ClothUnder = {
        "Base.ahzfitnessbra",
        "Base.ahzuwhighwaist_t",
        "Base.ahzuwtightsshort",
    },

    ClothBody = {
        "Base.ahztoplongsleeve",
        "Base.ahztoplongsleevecut",
        "Armor.Vest_BulletArmy",
        "Armor.Vest_BulletPolice",
        "Armor.Vest_BulletCivilian",
        "Armor.Boilersuit_Flying",
        "Armor.HazmatSuit",
        "Base.MPonchoGreenUP",
        "Base.MPonchoGreenDOWN",
        "Base.MPonchoYellowUP",
        "Base.MPonchoYellowDOWN",
        "Base.MPonchoShoulder",
        "Base.MPonchoShoulderDOWN",
        "Base.MPonchoShoulderYEL",
        "Base.MPonchoShoulderYELdown",
        "Base.MPonchoBlackUP",
        "Base.MPonchoBlackDOWN",
        "Base.MPonchoShoulderBLA",
        "Base.MPonchoShoulderBLAdown",
        "MoreTraits.AntiqueJacket",
        "MoreTraits.AntiqueVest",
        "Base.AnimeTshirt",
        "Base.Jacket_FBIlg",
        "Base.Jacket_FBIlgblack",
        "Base.Jacket_FBIlgconidfbi",
        "Base.Jacket_FBIlgblackconidFBI",
        "Base.Jacket_RIOTlgblack",
        "Base.Vest_Bulletfbi",
        "Base.Vest_Bulletfbigreen",
        "Base.Vest_BulletfbiRIOTLg",
        "Base.Vest_BulletRiotLG",
        "Base.Jacket_ATFclosed",
        "Base.Jacket_USMSHclosed",
        "Base.Jacket_DEAclosed",
        "Base.Vest_BulletRIOTlggeneric",
        "Base.Shirt_FormalWhiteFBIIDLG",
        "TheyKnew.MysteriousHazmat",
        "Base.Interceptor_Armor",
        "Base.Interceptor_Armor_s",
        "Base.Interceptor_Armor_v",
        "Base.Marpat_Jacket_w",
        "Base.Marpat_Jacket_d",
        "RotatorsClothing.TShirt_RotatorsBlack",
    },

    FoodP = {
        "BottlingFish.BottlingFishFillet",
        "BottlingFish.BottlingSalmon",
        "Bottling.BottlingChicken",
        "Bottling.BottlingSteak",
        "Bottling.BottlingFrogMeat",
        "Bottling.BottlingMeatPatty",
        "Bottling.BottlingMuttonChop",
        "Bottling.BottlingPorkChop",
        "Bottling.BottlingRabbitmeat",
        "Bottling.BottlingSmallanimalmeat",
        "Bottling.BottlingSmallbirdmeat",
        "Bottling.BottlingBacon",
        "Bottling.BottlingBaconBits",
        "Bottling.BottlingBaconRashers",
        "Bottling.BottlingHam",
        "ANL.SugarBeet",
        "ANL.SlicedSugarBeets",
        "ANL.GratedBerries",
        "BogaPizza.PizzaDough",
        "BogaPizza.PizzaCheese",
        "BogaPizza.PizzaSauced",
        "BogaPizza.PizzaEtna",
        "BogaPizza.PizzaHawaii",
        "BogaPizza.PizzaPineapple",
        "BogaPizza.PizzaHamMushroom",
        "BogaPizza.PizzaSeafood",
        "BogaPizza.PizzaNduja",
        "BogaPizza.PizzaRumHam",
        "BogaPizza.NdujaSausage",
        "BogaPizza.NdujaSausageSlice",
        "BogaPizza.ChiliPepper",
        "BogaPizza.DicedPineapple",
        "BogaPizza.RumHam",
        "BogaPizza.RumHamSlice",
        "icecreammaker.IceCreamChocolate",
        "icecreammaker.IceCreamStrawberry",
        "icecreammaker.IceCreamCaramel",
        "icecreammaker.IceCreamCookieDough",
        "icecreammaker.IceCreamCookiesCreme",
        "icecreammaker.ConeChocolate",
        "icecreammaker.ConeStrawberry",
        "icecreammaker.ConeCaramel",
        "icecreammaker.ConeCookieDough",
        "icecreammaker.ConeCookiesCreme",
        "MoreTraits.ZombPatty",
        "MattSimpleAddons.MSABlack_Cherry",
        "MattSimpleAddons.MSAmerican_Plumb",
        "MattSimpleAddons.MSARaspberries",
        "MattSimpleAddons.MSABlackBerries",
        "MattSimpleAddons.MSAMulberry",
    },

    Misc = {
        "Base.JarLidBoxs",
        "LactoseCrossbow.LCTestAttachment",
        "MoreTraits.PapierMache",
        "Base.CrazedRamblings",
        "Base.CrazedRamblings2",
        "Base.CrazedRamblings3",
        "Base.CrazedRamblings4",
    },

    FoodB = {
        "AAS.MountainDew",
        "AAS.Pepsi",
        "AAS.RCCola",
        "AAS.RootBeer",
        "AAS.FantaGrape",
        "AAS.GingerAle",
        "AAS.CocaCola",
        "AAS.DrPepper",
        "AAS.DietCoke",
        "AAS.MountainDewBox",
        "AAS.PepsiBox",
        "AAS.RCColaBox",
        "AAS.RootBeerBox",
        "AAS.FantaGrapeBox",
        "AAS.CocaColaBox",
        "AAS.DietCokeBox",
        "AAS.DrPepperBox",
        "AAS.GingerAleBox",
        "ANL.WildBerryWine",
        "BogaPizza.RumFull",
        "FuelAPI.LargePetrolCanWater",
        "MoreTraits.BloodBox",
    },

    Junk = {
        "AAS.MountainDewEmpty",
        "AAS.PepsiEmpty",
        "AAS.RootBeerEmpty",
        "AAS.CocaColaEmpty",
        "AAS.DietCokeEmpty",
        "AAS.GingerAleEmpty",
        "AAS.DrPepperEmpty",
        "AAS.FantaGrapeEmpty",
        "AAS.RCColaEmpty",
        "AAS.CrushedCan",
    },

    Craft = {
        "ANL.SmallSaltRock",
        "AxeRecrafting.AxeHandle",
        "AxeRecrafting.FireAxeHead",
        "AxeRecrafting.WoodAxeHead",
        "AxeRecrafting.HandAxeHead",
        "AxeRecrafting.MetalAxeHandle",
        "PrimitiveSurvival.PS_BarkStrip",
        "PrimitiveSurvival.PS_SmallRope",
        "PrimitiveSurvival.PS_BranchesBundle",
        "Base.GlassMold",
        "Base.GlassShard",
        "Base.GlassPane",
    },

    Cook = {
        "ANL.WildYeastBase",
        "ANL.JarOfYeast",
        "ANL.DryJarOfYeast",
        "ANL.DriedSugarBeets",
        "ANL.JarOfCrushedBerries",
        "ANL.JarOfVinegarBase",
    },

    LitR = {
        "ANL.AnlRenewMag1",
        "ANL.AnlRenewMag2",
        "AutoGate.AutoGateMag",
        "AI_HELI.HeliMag",
        "BetLock.LockpickingMag",
        "BetLock.AlarmMag",
        "ESYB.MagazineAllAboutBladeBevels",
        "ESYB.MagazineTableGrinderUserManual",
        "ESYB.MagazineJapaneseMastersSpecialEdition",
        "ESYB.MagazineTypicalSharpeningMistakes",
        "ESYB.MagazineHomemadeGrindingTools",
        "ExamineCorpse.nmMedicalMagazine1",
        "ExamineCorpse.nmMedicalMagazine2",
        "ISA.ISAMag1",
        "Base.Lyman49th_Manual",
        "MoreTraits.MedicalMag1",
        "MoreTraits.MedicalMag2",
        "MoreTraits.MedicalMag3",
        "MoreTraits.MedicalMag4",
        "MoreTraits.AntiqueMag1",
        "MoreTraits.AntiqueMag2",
        "MoreTraits.AntiqueMag3",
        "Base.RDCZHijackingMagazineVol1",
        "Base.EngineerMagazine1",
        "Base.EngineerMagazine2",
    },

    SurFarm = {
        "ANL.SugarBeetSeed",
        "ANL.SugarBeetBagSeed",
        "Defecation.HumanFeces",
        "waterPipes.WaterPipe",
        "waterPipes.WaterPipe2",
        "MCM.Avocadoseed",
        "MCM.Pepperseed",
        "MCM.Cornseed",
        "MCM.Eggplantseed",
        "MCM.Leekseed",
        "MCM.Lettuceseed",
        "MCM.Onionseed",
        "MCM.Watermelonseed",
        "MCM.Zucchiniseed",
        "MCM.AvocadoBagSeed",
        "MCM.PepperBagSeed",
        "MCM.CornBagSeed",
        "MCM.EggplantBagSeed",
        "MCM.LeekBagSeed",
        "MCM.LettuceBagSeed",
        "MCM.OnionBagSeed",
        "MCM.WatermelonBagSeed",
        "MCM.ZucchiniBagSeed",
        "XNTree.XNSaplingApple",
        "XNTree.XNSaplingBanana",
        "XNTree.XNSaplingCherry",
        "XNTree.XNSaplingLemon",
        "XNTree.XNSaplingOrange",
        "XNTree.XNSaplingPeach",
        "XNTree.XNSaplingPineapple",
    },

    Med = {
        "Antiserum.AntiserumChemicals",
        "Antiserum.AntiserumChemicalWorkstation",
        "Antiserum.AntiserumSample",
        "Antiserum.AntiserumTestTube",
        "Antiserum.AntiserumTestTubePack",
        "Antiserum.AntiserumJournalOfResearch",
        "Antiserum.AntiserumWeak",
        "Antiserum.AntiserumStrong",
        "Antiserum.AntiserumCure",
        "Antiserum.AntiserumUsedInjector",
        "Antiserum.AntiserumEmptyInjector",
        "Antiserum.AntiserumEmptyInjectorPack",
        "AntiserumTestKit.AntiserumTestKit",
        "CorpseStudyMod.MedicalJournal",
        "Defecation.AntiDiarrhealPillBox",
        "Defecation.AntiDiarrhealPill",
        "ExamineCorpse.nmMedicalStudiesJournal",
        "MoreTraits.ZombificationCure",
        "TheyKnew.Zomboxycycline",
        "TheyKnew.Zomboxivir",
    },

    ClothHead = {
        "Armor.Hat_NBCmask",
        "Armor.Hat_SPHhelmet",
        "Armor.Hat_GasMask",
        "Armor.Hat_BalaclavaFace",
        "Armor.Hat_BalaclavaFull",
        "Base.Hat_HardHat_Miner_With_Light",
        "Base.Hat_BaseballCapDEA",
        "Base.Hat_BaseballCapDEA_Reverse",
        "Base.Hat_BaseballCapATF",
        "Base.Hat_BaseballCapATF_Reverse",
        "Base.Hat_BaseballCapFBILG",
        "Base.Hat_BaseballCapFBILG_Reverse",
        "Base.Hat_blackRiotHelmetfbilg",
        "Base.Hat_USMC_Cap_w",
        "Base.Hat_USMC_Cap_d",
        "Base.Hat_PASGT_Helmet",
        "Base.Hat_TPASGT_Helmet",
        "RotatorsClothing.Hat_BaseballCapRotators",
        "RotatorsClothing.Hat_BaseballCapRotators_Reverse",
    },

    Elec = {
        "AutoGate.GateController",
        "ISA.SolarPanel",
        "ISA.ISAInverter",
        "ISA.DeepCycleBattery",
        "ISA.SuperBattery",
        "ISA.WiredCarBattery",
        "ISA.DIYBattery",
        "ISA.PowerBank",
        "ISA.SolarPanelFlat",
        "ISA.SolarPanelWall",
        "ISA.SolarPanelMounted",
        "ISA.SolarFailsafe",
        "rat.WalkieTalkie1Grid",
        "rat.WalkieTalkie2Grid",
        "rat.WalkieTalkie3Grid",
        "rat.WalkieTalkie4Grid",
        "rat.WalkieTalkie5Grid",
        "rat.WalkieTalkieMakeShiftGrid",
        "rat.HamRadio1Grid",
        "rat.HamRadio2Grid",
        "rat.HamRadioMakeShiftGrid",
        "rat.RadioRedGrid",
        "rat.RadioBlackGrid",
        "rat.RadioMakeShiftGrid",
        "SAPPHEATER.SmallHeater",
        "SAPPHEATER.OutdoorHeater",
        "SAPPHEATER.ElectricHeater",
        "SAPPHEATER.HeaterCircuit",
        "Base.Simple Remote Door Control Receiver",
        "Base.Master V2 Remote",
        "Base.Master V3 Remote",
        "Base.Remote Door Control Receiver",
    },

    CraftElec = {
        "AutoGate.GateComponents",
    },

    LitC = {
        "Base.BedfordMap",
        "ISA.Stash_RiversideW1",
        "ISA.Stash_RosewoodE1",
        "ISA.Stash_Louisville1",
        "SZ.Bunker01",
        "SZ.Bunker02",
        "SZ.Bunker03",
        "SZ.Bunker04",
        "SZ.TopSecret",
        "SZ.TopSecret2",
        "SZ.TopSecret3",
        "SZ.opmap1",
        "SZ.opmap2",
        "SZ.opmap3",
        "SZ.labmap1",
    },

    Tool = {
        "Base.BF_HeadLight",
        "Base.HandTorch_CK_LED",
        "Base.HandTorch_ManLite",
        "Base.HandTorch_Army1",
        "Base.HandTorch_Army2",
        "Base.Torch1",
        "Base.Torch2",
        "Base.Torch3",
        "Base.Torch4",
        "Base.Torch5",
        "Base.Torch6",
        "Base.Torch7",
        "Base.TorchArmy1",
        "Base.TorchArmy2",
        "Base.BF_EgenerexLite",
        "Base.BF_SpiffoLite",
        "Base.BF_OldFlashlight",
        "BetLock.BobbyPin",
        "BetLock.HandmadeBobbyPin",
        "TowingCar.TowBar",
        "Base.DoorsRepairKitMetal",
        "Base.DoorsRepairKitWood",
        "Base.DoorsRepairKitEpoxy",
        "Base.WaterPocket",
        "Base.IcePocket",
        "ESYB.Sandstone",
        "ESYB.HomemadeWhetstone",
        "ESYB.Whetstone",
        "ESYB.TableGrinder",
        "ESYB.TableGrinderWithoutWheels",
        "Base.LighterEmpty",
        "Ftool.Chainsaw",
        "Base.Lyman_TMag",
        "Base.Lee_LoadMaster",
        "MoreTraits.Thumper",
        "MoreTraits.BloodyCrowbar",
        "MoreTraits.AntiqueHammer",
        "Base.LighterFluid",
        "Base.Lighter",
        "Base.PlasticLighter_Black",
        "Base.PlasticLighter_Blue",
        "Base.PlasticLighter_Green",
        "Base.PlasticLighter_Orange",
        "Base.PlasticLighter_Purple",
        "Base.PlasticLighter_Red",
        "Base.PlasticLighter_Yellow",
        "spraypaint.SpraycanWhite",
        "spraypaint.SpraycanRed",
        "spraypaint.SpraycanBlue",
        "spraypaint.SpraycanGreen",
        "spraypaint.SpraycanOrange",
        "spraypaint.SpraycanYellow",
        "spraypaint.SpraycanViolet",
        "spraypaint.SpraycanBlack",
        "spraypaint.SpraycanCyan",
        "spraypaint.ChalkWhite",
        "spraypaint.ChalkRed",
        "spraypaint.ChalkBlue",
        "spraypaint.ChalkGreen",
        "spraypaint.ChalkOrange",
        "spraypaint.ChalkYellow",
        "spraypaint.ChalkViolet",
        "spraypaint.ChalkCyan",
        "FixAFlat.FixAFlat",
        "Base.EmptyLighter",
    },

    FoodN = {
        "BogaPizza.WhiteSauce",
        "BogaPizza.BBQSauce",
        "icecreammaker.IceCreamMix",
        "icecreammaker.IceCreamMixStrawberry",
        "icecreammaker.IceCreamMixCaramel",
        "icecreammaker.IceCreamMixCookieDough",
        "icecreammaker.IceCreamMixCookiesCreme",
        "Base.fhqPowderedMilkPouch",
    },

    LitE = {
        "DBDA.DBDA1",
        "DBDA.DBDA2",
        "DBDA.DBDA3",
        "DBDA.DBDA4",
        "DBDA.TW",
        "DBDA.TWSR",
        "DBDA.Carrie",
        "DBDA.Shine",
        "DBDA.Stand",
        "DBDA.Cujo",
        "DBDA.Pet",
        "DBDA.Green",
        "DBDA.Dream",
        "DBDA.Mist",
        "DBDA.Doc",
        "DBDA.Out",
        "DBDA.Who",
        "DBDA.It",
    },

    Drugs = {
        "CigaretteMod.CigarettesOne",
        "CigaretteMod.CigaretteCarton",
        "Base.PackOfSmokes",
        "Base.CartonOfSmokes",
        "Base.Cigarettes",
    },

    MediaG = {
        "Computer.Disc_Game",
    },

    Mech = {
        "Base.SmallTrunk0",
        "Base.NormalTrunk0",
        "Base.BigTrunk0",
        "Base.FrontCarDoor0",
        "Base.TrunkDoor0",
        "Base.GloveBox0",
        "Base.1500_Water_Tank1",
        "Base.1500_Water_Tank2",
        "Base.1500_Water_Tank3",
        "Base.3000_Water_Tank1",
        "Base.3000_Water_Tank2",
        "Base.3000_Water_Tank3",
        "Base.10000_Water_Tank1",
        "Base.10000_Water_Tank2",
        "Base.10000_Water_Tank3",
        "Base.3000_Water_Tank_Tainted1",
        "Base.3000_Water_Tank_Tainted2",
        "Base.3000_Water_Tank_Tainted3",
        "Base.RS_WaterFilter",
        "Base.FRSideContainer_RS1",
        "Base.FRSideContainer_RS2",
        "Base.FRSideContainer_RS3",
        "Rotators.750Tank2",
        "Rotators.DoubleOldTire2",
        "Rotators.DoubleNormalTire2",
        "Rotators.DoubleModernTire2",
        "Rotators.AxleOldTire2",
        "Rotators.AxleNormalTire2",
        "Rotators.AxleModernTire2",
        "Rotators.SemiTruckBullbar_Item2",
        "Rotators.SemiTruckArmorDoor_Item2",
        "Rotators.SemiTruckArmorFront_Item2",
        "Rotators.SemiTruckArmorRear_Item2",
        "Rotators.WaterTrailerTankLid1",
        "Rotators.WaterTrailerTankLid2",
        "Rotators.WaterTrailerTankPump1",
        "Rotators.WaterTrailerTankPump2",
        "Rotators.WaterTrailerTankFilter2",
    },

    LitS = {
        "DrivingSkill.DrivingSkill_BookDriving1",
        "DrivingSkill.DrivingSkill_BookDriving2",
        "DrivingSkill.DrivingSkill_BookDriving3",
        "DrivingSkill.DrivingSkill_BookDriving4",
        "DrivingSkill.DrivingSkill_BookDriving5",
        "Base.BookStrength1",
        "Base.BookStrength2",
        "Base.BookStrength3",
        "Base.BookStrength4",
        "Base.BookStrength5",
        "Base.BookFitness1",
        "Base.BookFitness2",
        "Base.BookFitness3",
        "Base.BookFitness4",
        "Base.BookFitness5",
        "Base.BookMedicalJournal",
        "Base.BookElectricManual",
        "ScavengerSkill.ScavengerSkill_BookScavenging1",
        "ScavengerSkill.ScavengerSkill_BookScavenging2",
        "ScavengerSkill.ScavengerSkill_BookScavenging3",
        "ScavengerSkill.ScavengerSkill_BookScavenging4",
        "ScavengerSkill.ScavengerSkill_BookScavenging5",
        "Base.SkillRecoveryJournal",
    },

    ClothBag = {
        "Base.SportsFannyPack",
        "Base.SportsFannyPackBack",
        "Base.FannyPackXL",
        "Base.FannyPackXLBack",
        "Base.Interceptor_Pouches",
        "Base.Interceptor_Pouches_Straps",
    },

    CraftMetal = {
        "FencingKit.FenceKit",
        "FencingKit.ChainWireRoll",
    },

    Cont = {
        "FuelAPI.LargePetrolCan",
        "LactoseCrossbow.LCQuiver",
        "tactorgsol.tactorgsol_admin",
        "tactorgsol.tactorgsol_large",
        "tactorgsol.tactorgsol_medium",
        "tactorgsol.tactorgsol_small",
        "WaterDispenser.WaterJugEmpty",
        "WaterDispenser.WaterJugWaterFull",
    },

    Fuel = {
        "FuelAPI.LargePetrolCanFull",
        "WaterDispenser.WaterJugPetrolFull",
    },

    CraftAmmo = {
        "Base.GunPowder",
        "Base.PrimerSM_Pack",
        "Base.PrimerLG_Pack",
        "Base.PrimerSG_Pack",
        "Base.Lead57_Pack",
        "Base.Lead9_Pack",
        "Base.Lead38_Pack",
        "Base.Lead45_Pack",
        "Base.Lead44_Pack",
        "Base.Lead50_Pack",
        "Base.Lead556_Pack",
        "Base.Lead545_Pack",
        "Base.Lead30_Pack",
        "Base.Lead00Buck_Pack",
    },

    Ammo = {
        "LactoseCrossbow.CrossbowBolt",
        "LactoseCrossbow.CrossbowBolts",
        "LactoseCrossbow.CrossbowBoltBundle",
        "LactoseCrossbow.LCCrossbowBoltAluminium",
        "LactoseCrossbow.LCCrossbowBoltAluminiumBundle",
    },

    WepPart = {
        "LactoseCrossbow.CrossbowUnstrung",
        "LactoseCrossbow.CrossbowStringString",
        "LactoseCrossbow.CrossbowStringNylon",
        "LactoseCrossbow.ModernCrossbowUnstrung",
        "LactoseCrossbow.CrossbowStringSteel",
        "Silencer.Silencer",
        "Silencer.HMSilencer",
    },

    WepBow = {
        "LactoseCrossbow.CrossbowStrungString",
        "LactoseCrossbow.CrossbowStrungNylon",
        "LactoseCrossbow.ModernCrossbowStrungSteel",
        "LactoseCrossbow.CrossbowStrungSteel",
        "LactoseCrossbow.ModernCrossbowStrungString",
        "LactoseCrossbow.ModernCrossbowStrungNylon",
    },

    Furn = {
        "Ladders.SteelLadder",
        "Ladders.WoodenLadder",
        "Onifurniture.MetalBox",
        "Onifurniture.LargeMetalBox",
        "Onifurniture.BigFridge1/2",
        "Onifurniture.BigFridge2/2",
        "Onifurniture.Fr1dge",
        "Onifurniture.TrashCan",
        "Onifurniture.CapacityCornerCounter",
        "Onifurniture.CapacityCounter",
        "Onifurniture.SmallContainer",
        "Onifurniture.BlackMetalBox",
        "Onifurniture.BoardsBox",
        "Onifurniture.PalletBoxes",
        "Onifurniture.ShippingBox",
        "Onifurniture.RedCounterCorner",
        "Onifurniture.RedCounter",
        "Onifurniture.RedWallCounter",
        "Onifurniture.WallCounter",
        "Onifurniture.SmallBookcase",
        "Onifurniture.ShoeCabinet",
        "Onifurniture.ModernDrawer",
        "Onifurniture.ModernDrawer2",
        "Onifurniture.ModernDrawer3",
        "Onifurniture.ModernStove",
        "Onifurniture.Wardrobe",
        "Onifurniture.ModernCloset",
        "SZ.Mov_Barrier01",
        "SZ.Mov_SecurityTerminal",
    },

    ClothBack = {
        "Base.AliceBackPack",
        "Base.AliceBackPackExtraPocket",
        "Base.AliceBackPackExtraPocket2",
        "Base.MilitaryAliceBackPack",
        "Base.MilitaryAliceBackPackExtraPocket",
        "MoreTraits.PackerBag",
        "MoreTraits.Bag_SmallHikingBag",
        "Base.Bag_ALICEpack_Pink",
        "PrimitiveSurvival.PS_SheetBag",
        "PrimitiveSurvival.PS_PrimitiveBag",
        "Base.Jaakari_L_Backpack",
        "Base.Jaakari_XL_Backpack",
        "TheyKnew.MysteriousSatchel",
    },

    CraftTailor = {
        "Base.ExtraPocket",
        "Base.NATT_Weapon",
        "Base.NATT_Remove_Weapon",
        "Base.NATT_ShortWeapon",
        "Base.NATT_Remove_ShortWeapon",
        "Base.NATT_Flashlight",
        "Base.NATT_Remove_Flashlight",
        "Base.NATT_Left",
        "Base.NATT_Remove_Left",
        "Base.NATT_Right",
        "Base.NATT_Remove_Right",
        "Base.NATT_UtilityLeft",
        "Base.NATT_Remove_UtilityLeft",
        "Base.NATT_UtilityRight",
        "Base.NATT_Remove_UtilityRight",
        "Base.NATT_Container",
        "Base.NATT_Remove_Container",
        "Base.NATT_ContainerSmallLeft",
        "Base.NATT_Remove_ContainerSmallLeft",
        "Base.NATT_ContainerSmallRight",
        "Base.NATT_Remove_ContainerSmallRight",
        "Base.NATT_Bedroll",
        "Base.NATT_Remove_Bedroll",
        "Base.NATT_AlicepackPouch",
        "Base.NATT_AlicepackNonPouch",
    },

    WepFire = {
        "Base.AZZK_pistol",
        "SZ.Barrys_Shotgun",
        "SZ.BCS_Shotgun",
        "SZ.Garrys_44",
        "SZ.BCS_Pistol",
    },

    SurTrap = {
        "Trap.PropaneTrap",
        "Trap.BearTrap",
        "Trap.BearTrapClosed",
        "Trap.SpikeTrap",
        "Trap.SpikeTrapClosed",
    },

    SurCamp = {
        "PrimitiveSurvival.PS_TwigsBundle",
        "Base.Sleepingbag",
        "Base.SleepingbagG",
        "Base.SleepingbagR",
        "Base.SleepingbagO",
        "Base.SleepingbagBK",
        "Base.SleepingbagLB",
        "Base.SleepingbagP",
        "Base.SleepingbagRolled",
        "Base.SleepingbagGRolled",
        "Base.SleepingbagRRolled",
        "Base.SleepingbagORolled",
        "Base.SleepingbagBKRolled",
        "Base.SleepingbagLBRolled",
        "Base.SleepingbagPRolled",
    },

    ClothAcc = {
        "Base.SlingA",
        "Base.SlingAalt",
        "Base.SlingAalt2",
        "Base.SlingAalt3",
    },

    Key = {
        "SZ.Key_BlueCard",
        "SZ.Key_RedCard",
        "SZ.Key_GreenCard",
        "SZ.Key_YellowCard",
        "SZ.Key_BlackCard",
        "SZ.Key_SystemL0",
    },

}