return {

    Craft = {
        "Base.Bellows",
        "Base.BucketPlasterFull",
        "Base.Doorknob",
        "Base.DuctTape",
        "Base.Firewood",
        "Base.FlintNodule",
        "Base.Garbagebag",
        "Base.Glue",
        "Base.Gravelbag",
        "Base.GunPowder",
        "Base.Hairspray",
        "Base.Handle",
        "Base.Hinge",
        "Base.Mattress",
        "Base.Nails",
        "Base.NailsBox",
        "Base.Paperclip",
        "Base.PaperclipBox",
        "Base.Pillow",
        "Base.PlasterPowder",
        "Base.PropaneTank",
        "Base.Rope",
        "Base.Sandbag",
        "Base.Scotchtape",
        "Base.Screws",
        "Base.ScrewsBox",
        "Base.SharpedStone",
        "Base.Sheet",
        "Base.Sparklers",
        "Base.Sponge",
        "Base.Stone",
        "Base.Stone2",
        "Base.TreeBranch",
        "Base.Twine",
        "Base.Wire",
        "Base.Woodglue",
        "Base.BucketConcreteFull",
        "Base.Handle",
        "Base.IronIngot",
        "Base.ConcretePowder",
    },

    CraftCarp = {
        "Base.BarbedWire",
        "Base.Drawer",
        "Base.Log",
        "Base.LogStacks2",
        "Base.LogStacks3",
        "Base.LogStacks4",
        "Base.Plank",
        "Base.Tarp",
        "Base.WoodenStick",
        "camping.TentPeg",
    },

    CraftElec = {
        "Base.Aluminum",
        "Base.Amplifier",
        "Base.Battery",
        "Base.Coldpack",
        "Base.ColdpackBox",
        "Base.ElectronicsScrap",
        "Base.HomeAlarm",
        "Base.LightBulb",
        "Base.LightBulbBlue",
        "Base.LightBulbCyan",
        "Base.LightBulbGreen",
        "Base.LightBulbMagenta",
        "Base.LightBulbOrange",
        "Base.LightBulbPink",
        "Base.LightBulbPurple",
        "Base.LightBulbRed",
        "Base.LightBulbYellow",
        "Base.MotionSensor",
        "Base.Receiver",
        "Base.Timer",
        "Base.TriggerCrafted",
        "Radio.ElectricWire",
        "Radio.RadioReceiver",
        "Radio.RadioTransmitter",
        "Radio.ScannerModule",
    },

    CraftMetal = {
        "Base.MetalBar",
        "Base.MetalPipe",
        "Base.ScrapMetal",
        "Base.SheetMetal",
        "Base.SmallSheetMetal",
        "Base.WeldingRods",
    },

    CraftTailor = {
        "Base.DenimStrips",
        "Base.DenimStripsDirty",
        "Base.LeatherStrips",
        "Base.LeatherStripsDirty",
        "Base.RippedSheets",
        "Base.RippedSheetsDirty",
        "Base.Thread",
        "Base.String",
        "Base.Yarn",
    },

}