return {

    Fuel = {
        "Base.RubberHose",
        "Base.PetrolCan",
        "Base.PetrolBleachBottle",
        "Base.PetrolPopBottle",
        "Base.WaterBottlePetrol",
        "Base.WhiskeyPetrol",
        "Base.WinePetrol",
    },

    SurCamp = {
        "Base.PercedWood",
        "Base.Twigs",
        "camping.CampfireKit",
        "camping.CampingTent",
        "camping.CampingTentKit",
        "camping.Flint",
        "camping.SteelAndFlint",
        "camping.SteelKnuckle",
        "Base.UnusableWood",
        "Base.Coal",
        "Base.FireWoodKit",
    },

    SurFish = {
        "Base.BaitFish",
        "Base.BrokenFishingNet",
        "Base.CraftedFishingRod",
        "Base.CraftedFishingRodTwineLine",
        "Base.FishingLine",
        "Base.FishingNet",
        "Base.FishingRod",
        "Base.FishingRodBreak",
        "Base.FishingRodTwineLine",
        "Base.FishingTackle",
        "Base.FishingTackle2",
    },

    SurTrap = {
        "Base.TrapBox",
        "Base.TrapCage",
        "Base.TrapCrate",
        "Base.TrapMouse",
        "Base.TrapSnare",
        "Base.TrapStick",
        "farming.BaconBits",
    },

    Tool = {
        "Base.BlowTorch",
        "Base.Candle",
        "Base.CandleLit",
        "Base.CarBatteryCharger",
        "Base.Corkscrew",
        "Base.Extinguisher",
        "Base.Fishing*",
        "Base.GardenSaw",
        "Base.Handiknife",
        "Base.HandTorch",
        "Base.Jack",
        "Base.KitchenTongs",
        "Base.Lighter",
        "Base.LugWrench",
        "Base.Matches",
        "Base.MortarPestle",
        "Base.Needle",
        "Base.Saw",
        "Base.SheetRope",
        "Base.StraightRazor",
        "Base.Spanner",
        "Base.Spoon",
        "Base.Tongs",
        "Base.TinOpener",
        "Base.TirePump",
        "Base.Torch",
        "Base.Umbrella*",
        "Base.WeldingMask",
        "farming.GardeningSprayCigarettes",
        "farming.GardeningSprayEmpty",
        "farming.GardeningSprayFull",
        "farming.GardeningSprayMilk",
        "Base.HandShovel",
        "farming.WateredCan",
        "farming.WateredCanFull",
    },

    ToolWeap = {
        "Base.Axe",
        "Base.AxeStone",
        "Base.BallPeenHammer",
        "Base.BallPeenHammerForged",
        "Base.BarBell",
        "Base.BreadKnife",
        "Base.CarvingFork",
        "Base.ClosedUmbrellaBlack",
        "Base.ClosedUmbrellaBlue",
        "Base.ClosedUmbrellaRed",
        "Base.ClosedUmbrellaWhite",
        "Base.ClubHammer",
        "Base.Crowbar",
        "Base.DumbBell",
        "Base.FlintKnife",
        "Base.Fork",
        "Base.Hammer",
        "Base.HammerStone",
        "Base.HandAxe",
        "Base.HandScythe",
        "Base.HuntingKnife",
        "Base.HuntingKnifeForged",
        "Base.IcePick",
        "Base.KitchenKnife",
        "Base.MasonsChisel",
        "Base.MeatCleaver",
        "Base.PickAxe",
        "Base.PipeWrench",
        "Base.Rake",
        "Base.Scissors",
        "Base.ScissorsForged",
        "Base.Screwdriver",
        "Base.ScrewdriverForged",
        "Base.ShortBat",
        "Base.Sledgehammer",
        "Base.Sledgehammer2",
        "Base.StoneMaul",
        "Base.StoneMaulLong",
        "Base.WoodAxe",
        "Base.WoodenMallet",
        "Base.Wrench",
        "Base.Shovel",
        "Base.Shovel2",
    }

}