return {

    Drugs = {
        "Base.Cigarettes",
        "Base.CigarettePack",
        "Base.TobaccoChewing",
        "Base.CigaretteRolled",
        "Base.CigaretteSingle",
        "Base.Cigar",
        "Base.SmokingPipe_Tobacco",
        "Base.Cigarillo",
        "Base.SmokingPipe",
    },

    Med = {
        "Base.AlcoholBandage",
        "Base.AlcoholedCottonBalls",
        "Base.AlcoholRippedSheets",
        "Base.AlcoholWipes",
        "Base.Antibiotics",
        "Base.Bandage",
        "Base.BandageDirty",
        "Base.Bandaid",
        "Base.BlackSage",
        "Base.Comfrey",
        "Base.ComfreyCataplasm",
        "Base.ComfreyDried",
        "Base.CommonMallow",
        "Base.CottonBalls",
        "Base.Disinfectant",
        "Base.FirstAidKit",
        "Base.Ginseng",
        "Base.LemonGrass",
        "Base.Pills",
        "Base.PillsAntiDep",
        "Base.PillsBeta",
        "Base.PillsSleepingTablets",
        "Base.PillsVitamins",
        "Base.Plantain",
        "Base.PlantainDried",
        "Base.PlantainCataplasm",
        "Base.Splint",
        "Base.SutureNeedle",
        "Base.SutureNeedleHolder",
        "Base.Tissue",
        "Base.TissueBox",
        "Base.ToiletPaper",
        "Base.Tweezers",
        "Base.WildGarlic",
        "Base.WildGarlicCataplasm",
        "Base.TongueDepressor",
        "Base.TongueDepressorBox",
    },

}